# Copyright (C) 2023 Dominik Kilian
# SPDX-License-Identifier: GPL-3.0-or-later

CLANG:=../../../ext/wasi-sdk/bin/clang --sysroot=../../../ext/wasi-sdk/share/wasi-sysroot
WASM_OPT:=../../../ext/binaryen/bin/wasm-opt
WASM_DIS:=../../../ext/binaryen/bin/wasm-dis

CFLAGS+=\
  -Wl,--no-entry -nostartfiles -Wl,--import-memory \
  -msign-ext -mexec-model=reactor -flto -Oz -g0 \
  -I../common -I../../../guest/c

OPTFLAGS+=-Oz

ifeq ($(OS),Windows_NT)
  WASI_SDK_URL:=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-mingw.tar.gz
  BINARYEN_URL:=https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-windows.tar.gz
else
  WASI_SDK_URL:=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
  BINARYEN_URL:=https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz
endif

all: ../$(TARGET).wasm

wat: all obj/$(TARGET).wat

cleanobj:
	rm -Rf obj

clean: cleanobj
	rm -f ../$(TARGET).wasm

obj/$(TARGET).wat: ../$(TARGET).wasm
	mkdir -p obj
	$(WASM_DIS) -o $@ $<

../$(TARGET).wasm: $(SRC) ./*.h ../common/*.h ../../../guest/c/*.h Makefile ../common/Makefile.common
	mkdir -p obj
	$(CLANG) $(CFLAGS) -o obj/$(TARGET)-no-opt $(SRC)
	$(WASM_OPT) $(OPTFLAGS) -o $@ obj/$(TARGET)-no-opt

get-tools: ../../../ext/wasi-sdk/bin/clang ../../../ext/binaryen/bin/wasm-opt

../../../ext/wasi-sdk/bin/clang:
	mkdir -p ../../../ext/wasi-sdk
	wget -O../../../ext/wasi-sdk.tar.gz $(WASI_SDK_URL)
	tar xzvf ../../../ext/wasi-sdk.tar.gz --strip-components=1 -C ../../../ext/wasi-sdk
	rm ../../../ext/wasi-sdk.tar.gz

../../../ext/binaryen/bin/wasm-opt:
	mkdir -p ../../../ext/binaryen
	wget -O../../../ext/binaryen.tar.gz $(BINARYEN_URL)
	tar xzvf ../../../ext/binaryen.tar.gz --strip-components=1 -C ../../../ext/binaryen
	rm ../../../ext/binaryen.tar.gz
