

#define TRIVM_EXT_REDUCE 0
#define TRIVM_EXT_INT64 0
#define TRIVM_EXT_FLOAT32 0
#define TRIVM_EXT_FLOAT64 0
#define TRIVM_ENABLE_STDLIB 0
#define TRIVM_ALIGN_MEMORY_ACCESS 0

#define TRIVM_FAULT_BYTECODE_BOUNDARY 0
#define TRIVM_FAULT_INVALID_INSTRUCTION 1
#define TRIVM_FAULT_WRITE_PROTECTED 2
#define TRIVM_FAULT_MEMORY_BOUNDARY 6
#define TRIVM_FAULT_DIVISION_BY_ZERO 7
#define TRIVM_FAULT_STACK_OVERFLOW 3
#define TRIVM_FAULT_STACK_UNDERFLOW 4
#define TRIVM_FAULT_STACK_UNALIGNED 5
#define TRIVM_FAULT_AUX_STACK_OVERFLOW 3
#define TRIVM_FAULT_AUX_STACK_UNDERFLOW 4
#define TRIVM_FAULT_AUX_STACK_UNALIGNED 5
#define TRIVM_FAULT_FLOAT_INVALID 5
#define TRIVM_FAULT_FLOAT_DIVISION_BY_ZERO 7
#define TRIVM_FAULT_FLOAT_OVERFLOW 7
#define TRIVM_FAULT_FLOAT_ 7


