
import * as fs from 'node:fs';
import * as path from 'node:path';

let source = `
/* Source code generated by the "res-gen.ts" script. Do not edit it manually. */
/* eslint-disable max-len */
/* eslint-disable quotes */
`;
let outputFile = process.argv[2];
for (let i = 3; i < process.argv.length; i++) {
    let inputFile = process.argv[i];
    let data = fs.readFileSync(inputFile, 'utf8');
    let name = path.basename(inputFile).replace(/[^a-z0-9]+/gi, '_').toUpperCase();
    source += `\n/* ${process.argv[i]} */\nexport const ${name} = ${JSON.stringify(data)};\n`;
}
fs.writeFileSync(outputFile, source);
