/* This file is automatically generated by Lemon from input grammar
** source file "src/lemonParser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 6 "src/lemonParser.y"
 #include "lemonParser.h" 
#line 31 "lemon/lemonParser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LEMON_EOL
#define LEMON_EOL                             1
#define LEMON_INSTRUCTION                     2
#define LEMON_PRAGMA                          3
#define LEMON_STRING                          4
#define LEMON_COLON                           5
#define LEMON_ASSIGN                          6
#define LEMON_COMMA                           7
#define LEMON_IDENTIFIER                      8
#define LEMON_BASE                            9
#define LEMON_QUESTION                       10
#define LEMON_OR                             11
#define LEMON_AND                            12
#define LEMON_BIT_OR                         13
#define LEMON_BIT_XOR                        14
#define LEMON_BIT_AND                        15
#define LEMON_EQ                             16
#define LEMON_NE                             17
#define LEMON_LT                             18
#define LEMON_GT                             19
#define LEMON_LE                             20
#define LEMON_GE                             21
#define LEMON_SHL                            22
#define LEMON_SHR                            23
#define LEMON_PLUS                           24
#define LEMON_MINUS                          25
#define LEMON_MUL                            26
#define LEMON_DIV                            27
#define LEMON_MOD                            28
#define LEMON_NOT                            29
#define LEMON_BIT_NOT                        30
#define LEMON_OPEN                           31
#define LEMON_CLOSE                          32
#define LEMON_DECIMAL                        33
#define LEMON_HEX                            34
#define LEMON_OCT                            35
#define LEMON_SOPEN                          36
#define LEMON_SCLOSE                         37
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    LemonParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is LemonParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    LemonParseARG_SDECL     A static variable declaration for the %extra_argument
**    LemonParseARG_PDECL     A parameter declaration for the %extra_argument
**    LemonParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    LemonParseARG_STORE     Code to store %extra_argument into yypParser
**    LemonParseARG_FETCH     Code to extract %extra_argument from yypParser
**    LemonParseCTX_*         As LemonParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 46
#define YYACTIONTYPE unsigned char
#define LemonParseTOKENTYPE  LemonToken 
typedef union {
  int yyinit;
  LemonParseTOKENTYPE yy0;
  LemonToken yy45;
  int yy52;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 2000
#endif
#define LemonParseARG_SDECL
#define LemonParseARG_PDECL
#define LemonParseARG_PARAM
#define LemonParseARG_FETCH
#define LemonParseARG_STORE
#define LemonParseCTX_SDECL  void* th ;
#define LemonParseCTX_PDECL , void* th 
#define LemonParseCTX_PARAM ,th 
#define LemonParseCTX_FETCH  void* th =yypParser->th ;
#define LemonParseCTX_STORE yypParser->th =th ;
#define YYNSTATE             84
#define YYNRULE              49
#define YYNRULE_WITH_ACTION  47
#define YYNTOKEN             38
#define YY_MAX_SHIFT         83
#define YY_MIN_SHIFTREDUCE   84
#define YY_MAX_SHIFTREDUCE   132
#define YY_ERROR_ACTION      133
#define YY_ACCEPT_ACTION     134
#define YY_NO_ACTION         135
#define YY_MIN_REDUCE        136
#define YY_MAX_REDUCE        184
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (1250)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   135,  150,  134,    3,  142,  150,  150,  150,   33,   67,
 /*    10 */   150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
 /*    20 */   150,  150,  150,  150,  150,  150,  150,  150,  150,  148,
 /*    30 */   141,  150,  150,  148,  148,  148,   33,   68,  148,  148,
 /*    40 */   148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
 /*    50 */   148,  148,  148,  148,  148,  148,  148,  181,   43,  148,
 /*    60 */   148,  181,   37,  181,   33,   69,  181,  181,  181,  181,
 /*    70 */   181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
 /*    80 */   181,  181,  181,  181,  181,  152,   79,    2,  181,  152,
 /*    90 */   140,  152,   33,   44,  152,   28,   27,   26,   25,   24,
 /*   100 */    23,   22,   21,   20,   19,   18,   17,   16,   15,   14,
 /*   110 */    13,   12,   11,  151,   72,  144,  152,  151,  135,  151,
 /*   120 */   135,    4,  151,  151,  151,  151,  151,  151,  151,  151,
 /*   130 */   151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
 /*   140 */   151,  149,  135,  151,  151,  149,  144,  149,   33,   45,
 /*   150 */   149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
 /*   160 */   149,  149,  149,  149,  149,  149,  149,  149,  149,  182,
 /*   170 */   135,  149,  149,  182,  135,  182,   33,   46,  182,  182,
 /*   180 */   182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
 /*   190 */   182,  182,  182,  182,  182,  182,  182,  180,   33,   47,
 /*   200 */   182,  180,  135,  180,   33,   48,  180,  180,  180,  180,
 /*   210 */   180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
 /*   220 */   180,  180,  180,  180,  180,  179,   33,   49,  180,  179,
 /*   230 */   135,  179,   33,   50,  179,  179,  179,  179,  179,  179,
 /*   240 */   179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
 /*   250 */   179,  179,  179,  178,   33,   51,  179,  178,  135,  178,
 /*   260 */    33,   52,  178,  178,  178,  178,  178,  178,  178,  178,
 /*   270 */   178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
 /*   280 */   178,  177,   33,   53,  178,  177,  135,  177,   33,   54,
 /*   290 */   177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
 /*   300 */   177,  177,  177,  177,  177,  177,  177,  177,  177,  176,
 /*   310 */    33,   55,  177,  176,  135,  176,   33,   56,  176,  176,
 /*   320 */   176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
 /*   330 */   176,  176,  176,  176,  176,  176,  176,  175,   33,   57,
 /*   340 */   176,  175,  135,  175,   33,   58,  175,  175,  175,  175,
 /*   350 */   175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
 /*   360 */   175,  175,  175,  175,  175,  174,   33,   59,  175,  174,
 /*   370 */   135,  174,   33,   60,  174,  174,  174,  174,  174,  174,
 /*   380 */   174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
 /*   390 */   174,  174,  174,  173,   33,   61,  174,  173,  135,  173,
 /*   400 */    33,   62,  173,  173,  173,  173,  173,  173,  173,  173,
 /*   410 */   173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
 /*   420 */   173,  172,   33,   63,  173,  172,  135,  172,   33,   64,
 /*   430 */   172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*   440 */   172,  172,  172,  172,  172,  172,  172,  172,  172,  171,
 /*   450 */    33,   65,  172,  171,  135,  171,   33,   34,  171,  171,
 /*   460 */   171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
 /*   470 */   171,  171,  171,  171,  171,  171,  171,  170,   33,   70,
 /*   480 */   171,  170,  135,  170,   77,    5,  170,  170,  170,  170,
 /*   490 */   170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
 /*   500 */   170,  170,  170,  170,  170,  169,  135,  135,  170,  169,
 /*   510 */   135,  169,  135,  135,  169,  169,  169,  169,  169,  169,
 /*   520 */   169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
 /*   530 */   169,  169,  169,  168,  135,  135,  169,  168,  135,  168,
 /*   540 */   135,  135,  168,  168,  168,  168,  168,  168,  168,  168,
 /*   550 */   168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
 /*   560 */   168,  167,  135,  135,  168,  167,  135,  167,  135,  135,
 /*   570 */   167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
 /*   580 */   167,  167,  167,  167,  167,  167,   13,   12,   11,  166,
 /*   590 */   135,  135,  167,  166,  135,  166,  135,  135,  166,  166,
 /*   600 */   166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
 /*   610 */   166,  166,  166,  166,   13,   12,   11,  165,  135,  135,
 /*   620 */   166,  165,  135,  165,  135,  135,  165,  165,  165,  165,
 /*   630 */   165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
 /*   640 */    15,   14,   13,   12,   11,  164,  135,  135,  165,  164,
 /*   650 */   135,  164,  135,  135,  164,  164,  164,  164,  164,  164,
 /*   660 */   164,  164,  164,  164,  164,  164,  164,  164,   15,   14,
 /*   670 */    13,   12,   11,  163,  135,  135,  164,  163,  135,  163,
 /*   680 */   135,  135,  163,  163,  163,  163,  163,  163,  163,  163,
 /*   690 */   163,  163,  163,  163,   17,   16,   15,   14,   13,   12,
 /*   700 */    11,  162,  135,  135,  163,  162,  135,  162,  135,  135,
 /*   710 */   162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
 /*   720 */   162,  162,   17,   16,   15,   14,   13,   12,   11,  161,
 /*   730 */   135,  135,  162,  161,  135,  161,  135,  135,  161,  161,
 /*   740 */   161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
 /*   750 */    17,   16,   15,   14,   13,   12,   11,  160,  135,  135,
 /*   760 */   161,  160,  135,  160,  135,  135,  160,  160,  160,  160,
 /*   770 */   160,  160,  160,  160,  160,  160,  160,  160,   17,   16,
 /*   780 */    15,   14,   13,   12,   11,  159,  135,  135,  160,  159,
 /*   790 */   135,  159,  135,  135,  159,  159,  159,  159,  159,  159,
 /*   800 */   159,  159,   21,   20,   19,   18,   17,   16,   15,   14,
 /*   810 */    13,   12,   11,  158,  135,  135,  159,  158,  135,  158,
 /*   820 */   135,  135,  158,  158,  158,  158,  158,  158,  158,  158,
 /*   830 */    21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
 /*   840 */    11,  157,  135,  135,  158,  157,  135,  157,  135,  135,
 /*   850 */   157,  157,  157,  157,  157,  157,   23,   22,   21,   20,
 /*   860 */    19,   18,   17,   16,   15,   14,   13,   12,   11,  156,
 /*   870 */   135,  135,  157,  156,  135,  156,  135,  135,  156,  156,
 /*   880 */   156,  156,  156,   24,   23,   22,   21,   20,   19,   18,
 /*   890 */    17,   16,   15,   14,   13,   12,   11,  155,  135,  135,
 /*   900 */   156,  155,  135,  155,  135,  135,  155,  155,  155,  155,
 /*   910 */    25,   24,   23,   22,   21,   20,   19,   18,   17,   16,
 /*   920 */    15,   14,   13,   12,   11,  154,  135,  135,  155,  154,
 /*   930 */   135,  154,  135,  135,  154,  154,  154,   26,   25,   24,
 /*   940 */    23,   22,   21,   20,   19,   18,   17,   16,   15,   14,
 /*   950 */    13,   12,   11,  153,  135,  135,  154,  153,  135,  153,
 /*   960 */   135,  135,  153,  153,   27,   26,   25,   24,   23,   22,
 /*   970 */    21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
 /*   980 */    11,  147,   73,   83,  153,   76,  135,  147,  135,  135,
 /*   990 */    30,   28,   27,   26,   25,   24,   23,   22,   21,   20,
 /*  1000 */    19,   18,   17,   16,   15,   14,   13,   12,   11,  146,
 /*  1010 */   135,  135,  147,  135,  135,  146,  135,  135,   30,   28,
 /*  1020 */    27,   26,   25,   24,   23,   22,   21,   20,   19,   18,
 /*  1030 */    17,   16,   15,   14,   13,   12,   11,  143,  135,  135,
 /*  1040 */   146,   82,   33,   66,   75,  135,   30,   28,   27,   26,
 /*  1050 */    25,   24,   23,   22,   21,   20,   19,   18,   17,   16,
 /*  1060 */    15,   14,   13,   12,   11,   30,   28,   27,   26,   25,
 /*  1070 */    24,   23,   22,   21,   20,   19,   18,   17,   16,   15,
 /*  1080 */    14,   13,   12,   11,   29,  135,  135,   41,  135,   30,
 /*  1090 */    28,   27,   26,   25,   24,   23,   22,   21,   20,   19,
 /*  1100 */    18,   17,   16,   15,   14,   13,   12,   11,  139,   36,
 /*  1110 */    35,  135,  149,  149,  135,   32,   31,  184,  184,  184,
 /*  1120 */   184,  183,   71,    1,   74,  184,  184,  135,  135,   32,
 /*  1130 */    31,   10,    9,  135,  135,  135,    8,    7,    6,  135,
 /*  1140 */    40,   39,   38,   80,  145,   36,   35,  138,  138,  138,
 /*  1150 */   138,   32,   31,  135,  135,  138,  138,  137,  137,  137,
 /*  1160 */   137,  136,  136,  136,  136,  137,  137,   10,    9,  136,
 /*  1170 */   136,  135,    8,    7,    6,  145,   40,   39,   38,   80,
 /*  1180 */    36,   35,  135,   78,  151,  151,   32,   31,   81,   33,
 /*  1190 */    66,   75,  135,  135,  135,  135,  135,  135,  135,  135,
 /*  1200 */   135,  135,   10,    9,  135,  135,  135,    8,    7,    6,
 /*  1210 */    42,   40,   39,   38,   80,   36,   35,  135,  135,  135,
 /*  1220 */   135,   32,   31,  135,  135,  135,  135,  135,  135,  135,
 /*  1230 */   135,  135,  135,  135,  135,  135,  135,   10,    9,  135,
 /*  1240 */   135,  135,    8,    7,    6,  135,   40,   39,   38,   80,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    46,    1,   38,   39,    1,    5,    6,    7,   43,   44,
 /*    10 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*    20 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*    30 */     1,   31,   32,    5,    6,    7,   43,   44,   10,   11,
 /*    40 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*    50 */    22,   23,   24,   25,   26,   27,   28,    1,   32,   31,
 /*    60 */    32,    5,   37,    7,   43,   44,   10,   11,   12,   13,
 /*    70 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*    80 */    24,   25,   26,   27,   28,    1,    9,   31,   32,    5,
 /*    90 */     1,    7,   43,   44,   10,   11,   12,   13,   14,   15,
 /*   100 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   110 */    26,   27,   28,    1,    1,    1,   32,    5,   46,    7,
 /*   120 */    46,    7,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   130 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   140 */    28,    1,   46,   31,   32,    5,   32,    7,   43,   44,
 /*   150 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   160 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   170 */    46,   31,   32,    5,   46,    7,   43,   44,   10,   11,
 /*   180 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   190 */    22,   23,   24,   25,   26,   27,   28,    1,   43,   44,
 /*   200 */    32,    5,   46,    7,   43,   44,   10,   11,   12,   13,
 /*   210 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   220 */    24,   25,   26,   27,   28,    1,   43,   44,   32,    5,
 /*   230 */    46,    7,   43,   44,   10,   11,   12,   13,   14,   15,
 /*   240 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   250 */    26,   27,   28,    1,   43,   44,   32,    5,   46,    7,
 /*   260 */    43,   44,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   270 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   280 */    28,    1,   43,   44,   32,    5,   46,    7,   43,   44,
 /*   290 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   300 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   310 */    43,   44,   32,    5,   46,    7,   43,   44,   10,   11,
 /*   320 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   330 */    22,   23,   24,   25,   26,   27,   28,    1,   43,   44,
 /*   340 */    32,    5,   46,    7,   43,   44,   10,   11,   12,   13,
 /*   350 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   360 */    24,   25,   26,   27,   28,    1,   43,   44,   32,    5,
 /*   370 */    46,    7,   43,   44,   10,   11,   12,   13,   14,   15,
 /*   380 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   390 */    26,   27,   28,    1,   43,   44,   32,    5,   46,    7,
 /*   400 */    43,   44,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   410 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   420 */    28,    1,   43,   44,   32,    5,   46,    7,   43,   44,
 /*   430 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   440 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   450 */    43,   44,   32,    5,   46,    7,   43,   44,   10,   11,
 /*   460 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   470 */    22,   23,   24,   25,   26,   27,   28,    1,   43,   44,
 /*   480 */    32,    5,   46,    7,    5,    6,   10,   11,   12,   13,
 /*   490 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   500 */    24,   25,   26,   27,   28,    1,   46,   46,   32,    5,
 /*   510 */    46,    7,   46,   46,   10,   11,   12,   13,   14,   15,
 /*   520 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   530 */    26,   27,   28,    1,   46,   46,   32,    5,   46,    7,
 /*   540 */    46,   46,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   550 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   560 */    28,    1,   46,   46,   32,    5,   46,    7,   46,   46,
 /*   570 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   580 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   590 */    46,   46,   32,    5,   46,    7,   46,   46,   10,   11,
 /*   600 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   610 */    22,   23,   24,   25,   26,   27,   28,    1,   46,   46,
 /*   620 */    32,    5,   46,    7,   46,   46,   10,   11,   12,   13,
 /*   630 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   640 */    24,   25,   26,   27,   28,    1,   46,   46,   32,    5,
 /*   650 */    46,    7,   46,   46,   10,   11,   12,   13,   14,   15,
 /*   660 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   670 */    26,   27,   28,    1,   46,   46,   32,    5,   46,    7,
 /*   680 */    46,   46,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   690 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   700 */    28,    1,   46,   46,   32,    5,   46,    7,   46,   46,
 /*   710 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   720 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   730 */    46,   46,   32,    5,   46,    7,   46,   46,   10,   11,
 /*   740 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   750 */    22,   23,   24,   25,   26,   27,   28,    1,   46,   46,
 /*   760 */    32,    5,   46,    7,   46,   46,   10,   11,   12,   13,
 /*   770 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   780 */    24,   25,   26,   27,   28,    1,   46,   46,   32,    5,
 /*   790 */    46,    7,   46,   46,   10,   11,   12,   13,   14,   15,
 /*   800 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   810 */    26,   27,   28,    1,   46,   46,   32,    5,   46,    7,
 /*   820 */    46,   46,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   830 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   840 */    28,    1,   46,   46,   32,    5,   46,    7,   46,   46,
 /*   850 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   860 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*   870 */    46,   46,   32,    5,   46,    7,   46,   46,   10,   11,
 /*   880 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   890 */    22,   23,   24,   25,   26,   27,   28,    1,   46,   46,
 /*   900 */    32,    5,   46,    7,   46,   46,   10,   11,   12,   13,
 /*   910 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   920 */    24,   25,   26,   27,   28,    1,   46,   46,   32,    5,
 /*   930 */    46,    7,   46,   46,   10,   11,   12,   13,   14,   15,
 /*   940 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   950 */    26,   27,   28,    1,   46,   46,   32,    5,   46,    7,
 /*   960 */    46,   46,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   970 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   980 */    28,    1,   40,   41,   32,   43,   46,    7,   46,   46,
 /*   990 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*  1000 */    20,   21,   22,   23,   24,   25,   26,   27,   28,    1,
 /*  1010 */    46,   46,   32,   46,   46,    7,   46,   46,   10,   11,
 /*  1020 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*  1030 */    22,   23,   24,   25,   26,   27,   28,    1,   46,   46,
 /*  1040 */    32,   42,   43,   44,   45,   46,   10,   11,   12,   13,
 /*  1050 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*  1060 */    24,   25,   26,   27,   28,   10,   11,   12,   13,   14,
 /*  1070 */    15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
 /*  1080 */    25,   26,   27,   28,    5,   46,   46,   32,   46,   10,
 /*  1090 */    11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*  1100 */    21,   22,   23,   24,   25,   26,   27,   28,    1,    2,
 /*  1110 */     3,   46,    5,    6,   46,    8,    9,    0,    1,    2,
 /*  1120 */     3,    0,    1,    2,    3,    8,    9,   46,   46,    8,
 /*  1130 */     9,   24,   25,   46,   46,   46,   29,   30,   31,   46,
 /*  1140 */    33,   34,   35,   36,    1,    2,    3,    0,    1,    2,
 /*  1150 */     3,    8,    9,   46,   46,    8,    9,    0,    1,    2,
 /*  1160 */     3,    0,    1,    2,    3,    8,    9,   24,   25,    8,
 /*  1170 */     9,   46,   29,   30,   31,   32,   33,   34,   35,   36,
 /*  1180 */     2,    3,   46,    4,    5,    6,    8,    9,   42,   43,
 /*  1190 */    44,   45,   46,   46,   46,   46,   46,   46,   46,   46,
 /*  1200 */    46,   46,   24,   25,   46,   46,   46,   29,   30,   31,
 /*  1210 */    32,   33,   34,   35,   36,    2,    3,   46,   46,   46,
 /*  1220 */    46,    8,    9,   46,   46,   46,   46,   46,   46,   46,
 /*  1230 */    46,   46,   46,   46,   46,   46,   46,   24,   25,   46,
 /*  1240 */    46,   46,   29,   30,   31,   46,   33,   34,   35,   36,
 /*  1250 */    46,   46,   46,   46,   38,   38,   38,   38,   38,   38,
 /*  1260 */    38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
 /*  1270 */    38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
 /*  1280 */    38,   38,   38,   38,   38,   38,   38,   38,
};
#define YY_SHIFT_COUNT    (83)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (1213)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */  1117, 1107, 1178, 1121, 1143, 1213, 1213, 1213, 1213, 1213,
 /*    10 */  1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213,
 /*    20 */  1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213, 1213,
 /*    30 */  1213,    0,   28,   56,   84,  112,  140,  168,  196,  224,
 /*    40 */   252,  280,  308,  336,  364,  392,  420,  448,  476,  504,
 /*    50 */   532,  560,  588,  616,  644,  672,  700,  728,  756,  784,
 /*    60 */   812,  840,  868,  896,  924,  952,  980, 1008, 1036, 1055,
 /*    70 */  1079, 1147, 1157, 1161, 1179,  114,  479,    3,   29,   25,
 /*    80 */    77,   26,   89,  113,
};
#define YY_REDUCE_COUNT (30)
#define YY_REDUCE_MIN   (-36)
#define YY_REDUCE_MAX   (1146)
static const short yy_reduce_ofst[] = {
 /*     0 */   -36,  999, 1146,  942,  -35,   -7,   21,   49,  105,  133,
 /*    10 */   155,  161,  183,  189,  211,  217,  239,  245,  267,  273,
 /*    20 */   295,  301,  323,  329,  351,  357,  379,  385,  407,  413,
 /*    30 */   435,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    10 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    20 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    30 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    40 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    50 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    60 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    70 */   133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
 /*    80 */   133,  133,  133,  133,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  LemonParseARG_SDECL                /* A place to hold %extra_argument */
  LemonParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void LemonParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "EOL",
  /*    2 */ "INSTRUCTION",
  /*    3 */ "PRAGMA",
  /*    4 */ "STRING",
  /*    5 */ "COLON",
  /*    6 */ "ASSIGN",
  /*    7 */ "COMMA",
  /*    8 */ "IDENTIFIER",
  /*    9 */ "BASE",
  /*   10 */ "QUESTION",
  /*   11 */ "OR",
  /*   12 */ "AND",
  /*   13 */ "BIT_OR",
  /*   14 */ "BIT_XOR",
  /*   15 */ "BIT_AND",
  /*   16 */ "EQ",
  /*   17 */ "NE",
  /*   18 */ "LT",
  /*   19 */ "GT",
  /*   20 */ "LE",
  /*   21 */ "GE",
  /*   22 */ "SHL",
  /*   23 */ "SHR",
  /*   24 */ "PLUS",
  /*   25 */ "MINUS",
  /*   26 */ "MUL",
  /*   27 */ "DIV",
  /*   28 */ "MOD",
  /*   29 */ "NOT",
  /*   30 */ "BIT_NOT",
  /*   31 */ "OPEN",
  /*   32 */ "CLOSE",
  /*   33 */ "DECIMAL",
  /*   34 */ "HEX",
  /*   35 */ "OCT",
  /*   36 */ "SOPEN",
  /*   37 */ "SCLOSE",
  /*   38 */ "root",
  /*   39 */ "prog",
  /*   40 */ "line",
  /*   41 */ "command",
  /*   42 */ "args",
  /*   43 */ "id",
  /*   44 */ "expr",
  /*   45 */ "argsnc",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "prog ::= prog line",
 /*   1 */ "line ::= command EOL",
 /*   2 */ "line ::= EOL",
 /*   3 */ "command ::= INSTRUCTION",
 /*   4 */ "command ::= INSTRUCTION args",
 /*   5 */ "command ::= PRAGMA STRING",
 /*   6 */ "command ::= id COLON",
 /*   7 */ "command ::= id ASSIGN expr",
 /*   8 */ "args ::= argsnc",
 /*   9 */ "args ::= argsnc COMMA",
 /*  10 */ "argsnc ::= argsnc COMMA expr",
 /*  11 */ "argsnc ::= expr",
 /*  12 */ "id ::= IDENTIFIER",
 /*  13 */ "id ::= INSTRUCTION",
 /*  14 */ "id ::= BASE",
 /*  15 */ "id ::= PRAGMA",
 /*  16 */ "expr ::= expr QUESTION expr COLON expr",
 /*  17 */ "expr ::= expr OR expr",
 /*  18 */ "expr ::= expr AND expr",
 /*  19 */ "expr ::= expr BIT_OR expr",
 /*  20 */ "expr ::= expr BIT_XOR expr",
 /*  21 */ "expr ::= expr BIT_AND expr",
 /*  22 */ "expr ::= expr EQ expr",
 /*  23 */ "expr ::= expr NE expr",
 /*  24 */ "expr ::= expr LT expr",
 /*  25 */ "expr ::= expr GT expr",
 /*  26 */ "expr ::= expr LE expr",
 /*  27 */ "expr ::= expr GE expr",
 /*  28 */ "expr ::= expr SHL expr",
 /*  29 */ "expr ::= expr SHR expr",
 /*  30 */ "expr ::= expr PLUS expr",
 /*  31 */ "expr ::= expr MINUS expr",
 /*  32 */ "expr ::= expr MUL expr",
 /*  33 */ "expr ::= expr DIV expr",
 /*  34 */ "expr ::= expr MOD expr",
 /*  35 */ "expr ::= PLUS expr",
 /*  36 */ "expr ::= MINUS expr",
 /*  37 */ "expr ::= NOT expr",
 /*  38 */ "expr ::= BIT_NOT expr",
 /*  39 */ "expr ::= id OPEN args CLOSE",
 /*  40 */ "expr ::= id OPEN CLOSE",
 /*  41 */ "expr ::= OPEN expr CLOSE",
 /*  42 */ "expr ::= DECIMAL",
 /*  43 */ "expr ::= HEX",
 /*  44 */ "expr ::= OCT",
 /*  45 */ "expr ::= id",
 /*  46 */ "expr ::= SOPEN BASE SCLOSE",
 /*  47 */ "root ::= prog",
 /*  48 */ "prog ::=",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to LemonParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void LemonParseInit(void *yypRawParser LemonParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  LemonParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to LemonParse and LemonParseFree.
*/
void *LemonParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) LemonParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    LemonParseCTX_STORE
    LemonParseInit(yypParser LemonParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
    case 42: /* args */
    case 45: /* argsnc */
{
#line 35 "src/lemonParser.y"
 lemonArgsFree(th, (yypminor->yy52)); 
#line 862 "lemon/lemonParser.c"
}
      break;
    case 44: /* expr */
{
#line 52 "src/lemonParser.y"
 lemonExprFree(th, (yypminor->yy52)); 
#line 869 "lemon/lemonParser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void LemonParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void LemonParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  LemonParseFinalize(p);
  (*freeProc)(p);
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int LemonParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int LemonParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   LemonParseARG_FETCH
   LemonParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
#line 9 "src/lemonParser.y"
 lemonStackOverflow(th); 
#line 1089 "lemon/lemonParser.c"
/******** End %stack_overflow code ********************************************/
   LemonParseARG_STORE /* Suppress warning about unused %extra_argument var */
   LemonParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  LemonParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    39,  /* (0) prog ::= prog line */
    40,  /* (1) line ::= command EOL */
    40,  /* (2) line ::= EOL */
    41,  /* (3) command ::= INSTRUCTION */
    41,  /* (4) command ::= INSTRUCTION args */
    41,  /* (5) command ::= PRAGMA STRING */
    41,  /* (6) command ::= id COLON */
    41,  /* (7) command ::= id ASSIGN expr */
    42,  /* (8) args ::= argsnc */
    42,  /* (9) args ::= argsnc COMMA */
    45,  /* (10) argsnc ::= argsnc COMMA expr */
    45,  /* (11) argsnc ::= expr */
    43,  /* (12) id ::= IDENTIFIER */
    43,  /* (13) id ::= INSTRUCTION */
    43,  /* (14) id ::= BASE */
    43,  /* (15) id ::= PRAGMA */
    44,  /* (16) expr ::= expr QUESTION expr COLON expr */
    44,  /* (17) expr ::= expr OR expr */
    44,  /* (18) expr ::= expr AND expr */
    44,  /* (19) expr ::= expr BIT_OR expr */
    44,  /* (20) expr ::= expr BIT_XOR expr */
    44,  /* (21) expr ::= expr BIT_AND expr */
    44,  /* (22) expr ::= expr EQ expr */
    44,  /* (23) expr ::= expr NE expr */
    44,  /* (24) expr ::= expr LT expr */
    44,  /* (25) expr ::= expr GT expr */
    44,  /* (26) expr ::= expr LE expr */
    44,  /* (27) expr ::= expr GE expr */
    44,  /* (28) expr ::= expr SHL expr */
    44,  /* (29) expr ::= expr SHR expr */
    44,  /* (30) expr ::= expr PLUS expr */
    44,  /* (31) expr ::= expr MINUS expr */
    44,  /* (32) expr ::= expr MUL expr */
    44,  /* (33) expr ::= expr DIV expr */
    44,  /* (34) expr ::= expr MOD expr */
    44,  /* (35) expr ::= PLUS expr */
    44,  /* (36) expr ::= MINUS expr */
    44,  /* (37) expr ::= NOT expr */
    44,  /* (38) expr ::= BIT_NOT expr */
    44,  /* (39) expr ::= id OPEN args CLOSE */
    44,  /* (40) expr ::= id OPEN CLOSE */
    44,  /* (41) expr ::= OPEN expr CLOSE */
    44,  /* (42) expr ::= DECIMAL */
    44,  /* (43) expr ::= HEX */
    44,  /* (44) expr ::= OCT */
    44,  /* (45) expr ::= id */
    44,  /* (46) expr ::= SOPEN BASE SCLOSE */
    38,  /* (47) root ::= prog */
    39,  /* (48) prog ::= */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -2,  /* (0) prog ::= prog line */
   -2,  /* (1) line ::= command EOL */
   -1,  /* (2) line ::= EOL */
   -1,  /* (3) command ::= INSTRUCTION */
   -2,  /* (4) command ::= INSTRUCTION args */
   -2,  /* (5) command ::= PRAGMA STRING */
   -2,  /* (6) command ::= id COLON */
   -3,  /* (7) command ::= id ASSIGN expr */
   -1,  /* (8) args ::= argsnc */
   -2,  /* (9) args ::= argsnc COMMA */
   -3,  /* (10) argsnc ::= argsnc COMMA expr */
   -1,  /* (11) argsnc ::= expr */
   -1,  /* (12) id ::= IDENTIFIER */
   -1,  /* (13) id ::= INSTRUCTION */
   -1,  /* (14) id ::= BASE */
   -1,  /* (15) id ::= PRAGMA */
   -5,  /* (16) expr ::= expr QUESTION expr COLON expr */
   -3,  /* (17) expr ::= expr OR expr */
   -3,  /* (18) expr ::= expr AND expr */
   -3,  /* (19) expr ::= expr BIT_OR expr */
   -3,  /* (20) expr ::= expr BIT_XOR expr */
   -3,  /* (21) expr ::= expr BIT_AND expr */
   -3,  /* (22) expr ::= expr EQ expr */
   -3,  /* (23) expr ::= expr NE expr */
   -3,  /* (24) expr ::= expr LT expr */
   -3,  /* (25) expr ::= expr GT expr */
   -3,  /* (26) expr ::= expr LE expr */
   -3,  /* (27) expr ::= expr GE expr */
   -3,  /* (28) expr ::= expr SHL expr */
   -3,  /* (29) expr ::= expr SHR expr */
   -3,  /* (30) expr ::= expr PLUS expr */
   -3,  /* (31) expr ::= expr MINUS expr */
   -3,  /* (32) expr ::= expr MUL expr */
   -3,  /* (33) expr ::= expr DIV expr */
   -3,  /* (34) expr ::= expr MOD expr */
   -2,  /* (35) expr ::= PLUS expr */
   -2,  /* (36) expr ::= MINUS expr */
   -2,  /* (37) expr ::= NOT expr */
   -2,  /* (38) expr ::= BIT_NOT expr */
   -4,  /* (39) expr ::= id OPEN args CLOSE */
   -3,  /* (40) expr ::= id OPEN CLOSE */
   -3,  /* (41) expr ::= OPEN expr CLOSE */
   -1,  /* (42) expr ::= DECIMAL */
   -1,  /* (43) expr ::= HEX */
   -1,  /* (44) expr ::= OCT */
   -1,  /* (45) expr ::= id */
   -3,  /* (46) expr ::= SOPEN BASE SCLOSE */
   -1,  /* (47) root ::= prog */
    0,  /* (48) prog ::= */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  LemonParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  LemonParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  LemonParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* prog ::= prog line */
#line 17 "src/lemonParser.y"
{ lemonResultVerify(th, yymsp[0].minor.yy52); }
#line 1308 "lemon/lemonParser.c"
        break;
      case 1: /* line ::= command EOL */
      case 9: /* args ::= argsnc COMMA */ yytestcase(yyruleno==9);
#line 22 "src/lemonParser.y"
{ yylhsminor.yy52 = yymsp[-1].minor.yy52; }
#line 1314 "lemon/lemonParser.c"
  yymsp[-1].minor.yy52 = yylhsminor.yy52;
        break;
      case 2: /* line ::= EOL */
#line 23 "src/lemonParser.y"
{ yymsp[0].minor.yy52 = -1; }
#line 1320 "lemon/lemonParser.c"
        break;
      case 3: /* command ::= INSTRUCTION */
#line 27 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonInstr(th, &yymsp[0].minor.yy0, 0); }
#line 1325 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 4: /* command ::= INSTRUCTION args */
#line 28 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonInstr(th, &yymsp[-1].minor.yy0, yymsp[0].minor.yy52); }
#line 1331 "lemon/lemonParser.c"
  yymsp[-1].minor.yy52 = yylhsminor.yy52;
        break;
      case 5: /* command ::= PRAGMA STRING */
#line 29 "src/lemonParser.y"
{ yymsp[-1].minor.yy52 = lemonPragma(th, &yymsp[0].minor.yy0); }
#line 1337 "lemon/lemonParser.c"
        break;
      case 6: /* command ::= id COLON */
#line 30 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonLabel(th, &yymsp[-1].minor.yy45); }
#line 1342 "lemon/lemonParser.c"
  yymsp[-1].minor.yy52 = yylhsminor.yy52;
        break;
      case 7: /* command ::= id ASSIGN expr */
#line 31 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonAssign(th, &yymsp[-2].minor.yy45, yymsp[0].minor.yy52); }
#line 1348 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 8: /* args ::= argsnc */
#line 36 "src/lemonParser.y"
{ yylhsminor.yy52 = yymsp[0].minor.yy52; }
#line 1354 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 10: /* argsnc ::= argsnc COMMA expr */
#line 40 "src/lemonParser.y"
{ yylhsminor.yy52 = yymsp[-2].minor.yy52; lemonArgsAppend(th, yylhsminor.yy52, yymsp[0].minor.yy52); }
#line 1360 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 11: /* argsnc ::= expr */
#line 41 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonArgsCreate(th); lemonArgsAppend(th, yylhsminor.yy52, yymsp[0].minor.yy52); }
#line 1366 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 12: /* id ::= IDENTIFIER */
      case 13: /* id ::= INSTRUCTION */ yytestcase(yyruleno==13);
      case 14: /* id ::= BASE */ yytestcase(yyruleno==14);
      case 15: /* id ::= PRAGMA */ yytestcase(yyruleno==15);
#line 45 "src/lemonParser.y"
{ yylhsminor.yy45 = yymsp[0].minor.yy0; }
#line 1375 "lemon/lemonParser.c"
  yymsp[0].minor.yy45 = yylhsminor.yy45;
        break;
      case 16: /* expr ::= expr QUESTION expr COLON expr */
#line 57 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprTernary(th, yymsp[-4].minor.yy52, yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1381 "lemon/lemonParser.c"
  yymsp[-4].minor.yy52 = yylhsminor.yy52;
        break;
      case 17: /* expr ::= expr OR expr */
#line 61 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'O', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1387 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 18: /* expr ::= expr AND expr */
#line 63 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'A', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1393 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 19: /* expr ::= expr BIT_OR expr */
#line 65 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '|', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1399 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 20: /* expr ::= expr BIT_XOR expr */
#line 67 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '^', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1405 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 21: /* expr ::= expr BIT_AND expr */
#line 69 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '&', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1411 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 22: /* expr ::= expr EQ expr */
#line 73 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'E', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1417 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 23: /* expr ::= expr NE expr */
#line 74 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'N', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1423 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 24: /* expr ::= expr LT expr */
#line 76 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '<', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1429 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 25: /* expr ::= expr GT expr */
#line 77 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '>', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1435 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 26: /* expr ::= expr LE expr */
#line 78 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'L', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1441 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 27: /* expr ::= expr GE expr */
#line 79 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'G', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1447 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 28: /* expr ::= expr SHL expr */
#line 83 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'r', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1453 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 29: /* expr ::= expr SHR expr */
#line 84 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, 'l', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1459 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 30: /* expr ::= expr PLUS expr */
#line 88 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '+', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1465 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 31: /* expr ::= expr MINUS expr */
#line 89 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '-', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1471 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 32: /* expr ::= expr MUL expr */
#line 91 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '*', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1477 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 33: /* expr ::= expr DIV expr */
#line 92 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '/', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1483 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 34: /* expr ::= expr MOD expr */
#line 93 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprBinOp(th, '%', yymsp[-2].minor.yy52, yymsp[0].minor.yy52); }
#line 1489 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 35: /* expr ::= PLUS expr */
#line 97 "src/lemonParser.y"
{ yymsp[-1].minor.yy52 = yymsp[0].minor.yy52; }
#line 1495 "lemon/lemonParser.c"
        break;
      case 36: /* expr ::= MINUS expr */
#line 98 "src/lemonParser.y"
{ yymsp[-1].minor.yy52 = lemonExprUnOp(th, 'M', yymsp[0].minor.yy52); }
#line 1500 "lemon/lemonParser.c"
        break;
      case 37: /* expr ::= NOT expr */
#line 99 "src/lemonParser.y"
{ yymsp[-1].minor.yy52 = lemonExprUnOp(th, '!', yymsp[0].minor.yy52); }
#line 1505 "lemon/lemonParser.c"
        break;
      case 38: /* expr ::= BIT_NOT expr */
#line 100 "src/lemonParser.y"
{ yymsp[-1].minor.yy52 = lemonExprUnOp(th, '~', yymsp[0].minor.yy52); }
#line 1510 "lemon/lemonParser.c"
        break;
      case 39: /* expr ::= id OPEN args CLOSE */
#line 103 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprCall(th, &yymsp[-3].minor.yy45, yymsp[-1].minor.yy52); }
#line 1515 "lemon/lemonParser.c"
  yymsp[-3].minor.yy52 = yylhsminor.yy52;
        break;
      case 40: /* expr ::= id OPEN CLOSE */
#line 104 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprCall(th, &yymsp[-2].minor.yy45, 0); }
#line 1521 "lemon/lemonParser.c"
  yymsp[-2].minor.yy52 = yylhsminor.yy52;
        break;
      case 41: /* expr ::= OPEN expr CLOSE */
#line 107 "src/lemonParser.y"
{ yymsp[-2].minor.yy52 = yymsp[-1].minor.yy52; }
#line 1527 "lemon/lemonParser.c"
        break;
      case 42: /* expr ::= DECIMAL */
#line 110 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprNumber(th, &yymsp[0].minor.yy0, 10); }
#line 1532 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 43: /* expr ::= HEX */
#line 111 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprNumber(th, &yymsp[0].minor.yy0, 16); }
#line 1538 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 44: /* expr ::= OCT */
#line 112 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprNumber(th, &yymsp[0].minor.yy0, 8); }
#line 1544 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 45: /* expr ::= id */
#line 113 "src/lemonParser.y"
{ yylhsminor.yy52 = lemonExprIdentifier(th, &yymsp[0].minor.yy45); }
#line 1550 "lemon/lemonParser.c"
  yymsp[0].minor.yy52 = yylhsminor.yy52;
        break;
      case 46: /* expr ::= SOPEN BASE SCLOSE */
#line 114 "src/lemonParser.y"
{ yymsp[-2].minor.yy52 = lemonExprBase(th, &yymsp[-1].minor.yy0); }
#line 1556 "lemon/lemonParser.c"
        break;
      default:
      /* (47) root ::= prog */ yytestcase(yyruleno==47);
      /* (48) prog ::= */ yytestcase(yyruleno==48);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 10 "src/lemonParser.y"
 lemonFailure(th); 
#line 1604 "lemon/lemonParser.c"
/************ End %parse_failure code *****************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  LemonParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 8 "src/lemonParser.y"
 lemonError(th); 
#line 1625 "lemon/lemonParser.c"
/************ End %syntax_error code ******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "LemonParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void LemonParse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  LemonParseTOKENTYPE yyminor       /* The value for the token */
  LemonParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  LemonParseCTX_FETCH
  LemonParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor LemonParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int LemonParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
