# Copyright (C) 2023 Dominik Kilian
# SPDX-License-Identifier: GPL-3.0-or-later

CLANG:=../../devtools/wasi-sdk/bin/clang --sysroot=../../devtools/wasi-sdk/share/wasi-sysroot
WASM_OPT:=../../devtools/binaryen/bin/wasm-opt
WASM_DIS:=../../devtools/binaryen/bin/wasm-dis

CFLAGS+=\
  -Wl,--no-entry -nostartfiles -Wl,--import-memory \
  -msign-ext -mexec-model=reactor -flto -Oz -g0 \
  -I../common

ifeq ($(OS),Windows_NT)
  WASI_SDK_URL:=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-mingw.tar.gz
  BINARYEN_URL:=https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-windows.tar.gz
else
  WASI_SDK_URL:=https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
  BINARYEN_URL:=https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz
endif

all: ../../dist/data/lib/$(TARGET).wasm

wat: all obj/$(TARGET).wat

obj/$(TARGET).wat: obj/$(TARGET).wasm
	$(WASM_DIS) -o $@ $<

cleanobj:
	rm -Rf obj

clean: cleanobj
	rm -R ../../lib/*

../../dist/data/lib/$(TARGET).wasm: obj/$(TARGET).wasm
	mkdir -p ../../dist/data/lib
	cp obj/$(TARGET).wasm ../../dist/data/lib/$(TARGET).wasm

obj/$(TARGET).wasm: $(SRC) ./*.h ../common/*.h Makefile ../common/Makefile.common
	mkdir -p obj
	$(CLANG) $(CFLAGS) -o $@-no-opt $(SRC)
	$(WASM_OPT) -Oz -o $@ $@-no-opt
	#cp $@-no-opt $@

get-tools: ../../devtools/wasi-sdk/bin/clang ../../devtools/binaryen/bin/wasm-opt

../../devtools/wasi-sdk/bin/clang:
	mkdir -p ../../devtools/wasi-sdk
	wget -O../../devtools/wasi-sdk.tar.gz $(WASI_SDK_URL)
	tar xzvf ../../devtools/wasi-sdk.tar.gz --strip-components=1 -C ../../devtools/wasi-sdk
	rm ../../devtools/wasi-sdk.tar.gz

../../devtools/binaryen/bin/wasm-opt:
	mkdir -p ../../devtools/binaryen
	wget -O../../devtools/binaryen.tar.gz $(BINARYEN_URL)
	tar xzvf ../../devtools/binaryen.tar.gz --strip-components=1 -C ../../devtools/binaryen
	rm ../../devtools/binaryen.tar.gz
