
/* Source code generated by the "res-gen.ts" script. Do not edit it manually. */
/* eslint-disable max-len */
/* eslint-disable quotes */

/* tools/asm/res/args.txt */
export const ARGS_TXT = "\r\n :# `triasm` command line arguments\r\n :\r\n USAGE:\r\n :```\r\n :triasm [options] <input>\r\n :```\r\n ;    triasm [options] <input>\r\n\r\n Compile triASM source code into triVM bytecode.\r\n\r\n:Path[1] <input>\r\n    The input triASM source code.\r\n\r\n-o\r\n--output:Path <file>\r\n    Put output to this file.\r\n\r\n--version:!version\r\n    Print tool version.\r\n\r\n--help:!help\r\n    Print this help text.\r\n\r\n--help-md:!markdown\r\n    Display this information in Markdown format.\r\n";
