/* This file is automatically generated by Lemon from input grammar
** source file "src/triasmParser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 2 "src/triasmParser.y"
 #include "triasmParser.h" 
#line 31 "lemon/triasmParser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LEMON_QUESTION
#define LEMON_QUESTION                        1
#define LEMON_BIT_OR                          2
#define LEMON_BIT_AND                         3
#define LEMON_MUL                             4
#define LEMON_DIV                             5
#define LEMON_MOD                             6
#define LEMON_PLUS                            7
#define LEMON_MINUS                           8
#define LEMON_EOL                             9
#define LEMON_COLON                          10
#define LEMON_ASSIGN                         11
#define LEMON_STRING                         12
#define LEMON_COMMA                          13
#define LEMON_IDENTIFIER                     14
#define LEMON_INSTRUCTION                    15
#define LEMON_DIRECTIVE                      16
#define LEMON_BASE                           17
#define LEMON_NUMBER                         18
#define LEMON_SOPEN                          19
#define LEMON_SCLOSE                         20
#define LEMON_OPEN                           21
#define LEMON_CLOSE                          22
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    LemonParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is LemonParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    LemonParseARG_SDECL     A static variable declaration for the %extra_argument
**    LemonParseARG_PDECL     A parameter declaration for the %extra_argument
**    LemonParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    LemonParseARG_STORE     Code to store %extra_argument into yypParser
**    LemonParseARG_FETCH     Code to extract %extra_argument from yypParser
**    LemonParseCTX_*         As LemonParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 32
#define YYACTIONTYPE unsigned char
#define LemonParseTOKENTYPE  LemonToken* 
typedef union {
  int yyinit;
  LemonParseTOKENTYPE yy0;
  LemonArgs* yy11;
  LemonToken* yy19;
  LemonCommand* yy33;
  LemonExpr* yy41;
  LemonProg* yy54;
  void* yy57;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 2000
#endif
#define LemonParseARG_SDECL
#define LemonParseARG_PDECL
#define LemonParseARG_PARAM
#define LemonParseARG_FETCH
#define LemonParseARG_STORE
#define LemonParseCTX_SDECL  Lemon* lemonState ;
#define LemonParseCTX_PDECL , Lemon* lemonState 
#define LemonParseCTX_PARAM ,lemonState 
#define LemonParseCTX_FETCH  Lemon* lemonState =yypParser->lemonState ;
#define LemonParseCTX_STORE yypParser->lemonState =lemonState ;
#define YYNSTATE             54
#define YYNRULE              34
#define YYNRULE_WITH_ACTION  34
#define YYNTOKEN             23
#define YY_MAX_SHIFT         53
#define YY_MIN_SHIFTREDUCE   54
#define YY_MAX_SHIFTREDUCE   87
#define YY_ERROR_ACTION      88
#define YY_ACCEPT_ACTION     89
#define YY_NO_ACTION         90
#define YY_MIN_REDUCE        91
#define YY_MAX_REDUCE        124
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (410)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    90,  108,   90,  108,  108,  108,  108,  108,  108,  108,
 /*    10 */   108,  108,    8,  108,    6,   11,   10,    9,   14,   13,
 /*    20 */   100,  108,  108,  105,   33,  105,  105,  105,  105,  105,
 /*    30 */   105,  105,  105,  105,   51,  105,   49,   47,   21,   36,
 /*    40 */    43,   53,    1,  105,  105,   44,   48,   99,   21,   36,
 /*    50 */    89,    2,  110,  110,  107,  107,  110,   42,  110,  110,
 /*    60 */   110,  110,  110,  110,   90,  110,   90,  109,  109,  106,
 /*    70 */   106,  109,   90,  109,  109,  109,  109,  109,  109,  123,
 /*    80 */   109,    6,   11,   10,    9,   14,   13,  123,  123,   90,
 /*    90 */   112,  123,  112,  112,  112,  112,  112,  112,  112,  112,
 /*   100 */   123,    8,  112,    6,   11,   10,    9,   14,   13,  104,
 /*   110 */     3,  112,  107,  104,  107,  107,  107,  107,  107,  107,
 /*   120 */   107,  107,  104,    8,  107,    6,   11,   10,    9,   14,
 /*   130 */    13,  103,  107,  107,  106,  103,  106,  106,  106,  106,
 /*   140 */   106,  106,  106,  106,  103,    8,  106,    6,   11,   10,
 /*   150 */     9,   14,   13,   90,  106,  106,  115,   90,  115,  115,
 /*   160 */   115,  115,  115,  115,  115,  115,   32,  122,  115,  122,
 /*   170 */   122,  122,  122,  122,  122,  122,  122,  115,  116,  122,
 /*   180 */   116,  116,  116,  116,  116,  116,  116,  116,  122,  117,
 /*   190 */   116,  117,  117,  117,  117,  117,  117,  117,  117,  116,
 /*   200 */   124,  117,  124,   11,   10,    9,   14,   13,  124,  124,
 /*   210 */   117,  120,  124,  120,  120,  120,  120,   14,   13,  120,
 /*   220 */   120,  124,  119,  120,  119,  119,  119,  119,   14,   13,
 /*   230 */   119,  119,  120,  118,  119,  118,  118,  118,  118,   14,
 /*   240 */    13,  118,  118,  119,  114,  118,  114,  114,  114,  114,
 /*   250 */   114,  114,  114,  114,  118,  113,  114,  113,  113,  113,
 /*   260 */   113,  113,  113,  113,  113,  114,  121,  113,  121,  121,
 /*   270 */   121,  121,  121,  121,  121,  121,  113,  111,  121,  111,
 /*   280 */   111,  111,  111,  111,  111,  111,  111,  121,   90,  111,
 /*   290 */    21,   38,  102,    5,   96,  102,   90,   45,  111,   17,
 /*   300 */    23,   22,   16,   35,   52,   90,   12,    5,   21,   27,
 /*   310 */    21,   28,   90,   17,   23,   22,   16,   35,   52,   97,
 /*   320 */    12,   25,    5,   15,   21,   20,   50,    4,   17,   23,
 /*   330 */    22,   16,   35,   52,    8,   12,    6,   11,   10,    9,
 /*   340 */    14,   13,   93,    7,   90,   21,   39,   21,   29,   21,
 /*   350 */    30,   93,   91,   21,   31,   90,   93,   93,   93,   93,
 /*   360 */   101,   41,   95,  101,   21,   40,   17,   19,   18,   16,
 /*   370 */    90,   95,   94,   21,   26,   90,   95,   95,   95,   95,
 /*   380 */    90,   94,   92,   21,   24,   90,   94,   94,   94,   94,
 /*   390 */    90,   92,   98,   21,   37,   46,   92,   92,   92,   92,
 /*   400 */    15,   90,   90,   90,   90,   90,   90,   90,   90,   34,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    32,    1,   32,    3,    4,    5,    6,    7,    8,    9,
 /*    10 */    10,   11,    1,   13,    3,    4,    5,    6,    7,    8,
 /*    20 */     9,   21,   22,    1,   20,    3,    4,    5,    6,    7,
 /*    30 */     8,    9,   10,   11,   17,   13,   28,   29,   30,   31,
 /*    40 */    25,   26,   27,   21,   22,   30,   28,    9,   30,   31,
 /*    50 */    23,   24,    8,    9,   10,   11,   12,    9,   14,   15,
 /*    60 */    16,   17,   18,   19,   32,   21,   32,    8,    9,   10,
 /*    70 */    11,   12,   32,   14,   15,   16,   17,   18,   19,    1,
 /*    80 */    21,    3,    4,    5,    6,    7,    8,    9,   10,   32,
 /*    90 */     1,   13,    3,    4,    5,    6,    7,    8,    9,   10,
 /*   100 */    22,    1,   13,    3,    4,    5,    6,    7,    8,    9,
 /*   110 */    21,   22,    1,   13,    3,    4,    5,    6,    7,    8,
 /*   120 */     9,   10,   22,    1,   13,    3,    4,    5,    6,    7,
 /*   130 */     8,    9,   21,   22,    1,   13,    3,    4,    5,    6,
 /*   140 */     7,    8,    9,   10,   22,    1,   13,    3,    4,    5,
 /*   150 */     6,    7,    8,   32,   21,   22,    1,   32,    3,    4,
 /*   160 */     5,    6,    7,    8,    9,   10,   22,    1,   13,    3,
 /*   170 */     4,    5,    6,    7,    8,    9,   10,   22,    1,   13,
 /*   180 */     3,    4,    5,    6,    7,    8,    9,   10,   22,    1,
 /*   190 */    13,    3,    4,    5,    6,    7,    8,    9,   10,   22,
 /*   200 */     1,   13,    3,    4,    5,    6,    7,    8,    9,   10,
 /*   210 */    22,    1,   13,    3,    4,    5,    6,    7,    8,    9,
 /*   220 */    10,   22,    1,   13,    3,    4,    5,    6,    7,    8,
 /*   230 */     9,   10,   22,    1,   13,    3,    4,    5,    6,    7,
 /*   240 */     8,    9,   10,   22,    1,   13,    3,    4,    5,    6,
 /*   250 */     7,    8,    9,   10,   22,    1,   13,    3,    4,    5,
 /*   260 */     6,    7,    8,    9,   10,   22,    1,   13,    3,    4,
 /*   270 */     5,    6,    7,    8,    9,   10,   22,    1,   13,    3,
 /*   280 */     4,    5,    6,    7,    8,    9,   10,   22,   32,   13,
 /*   290 */    30,   31,    9,    8,    9,   12,   32,   12,   22,   14,
 /*   300 */    15,   16,   17,   18,   19,   32,   21,    8,   30,   31,
 /*   310 */    30,   31,   32,   14,   15,   16,   17,   18,   19,    9,
 /*   320 */    21,   22,    8,   13,   30,   31,   10,   11,   14,   15,
 /*   330 */    16,   17,   18,   19,    1,   21,    3,    4,    5,    6,
 /*   340 */     7,    8,    0,   10,   32,   30,   31,   30,   31,   30,
 /*   350 */    31,    9,    0,   30,   31,   32,   14,   15,   16,   17,
 /*   360 */     9,    9,    0,   12,   30,   31,   14,   15,   16,   17,
 /*   370 */    32,    9,    0,   30,   31,   32,   14,   15,   16,   17,
 /*   380 */    32,    9,    0,   30,   31,   32,   14,   15,   16,   17,
 /*   390 */    32,    9,    9,   30,   31,   12,   14,   15,   16,   17,
 /*   400 */    13,   32,   32,   32,   32,   32,   32,   32,   32,   22,
 /*   410 */    32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
 /*   420 */    32,   32,   32,   32,   23,   23,   23,   23,   23,   23,
 /*   430 */    23,   23,   23,
};
#define YY_SHIFT_COUNT    (53)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (387)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   342,  285,  352,  299,  314,  314,  314,  314,  314,  314,
 /*    10 */   314,  314,  314,  314,  314,  314,    0,   22,   44,   59,
 /*    20 */    78,   89,  111,  133,  155,  166,  177,  188,  199,  210,
 /*    30 */   221,  232,  243,  254,  265,  276,  100,  122,   11,  333,
 /*    40 */   144,  362,  372,  382,  316,  283,  351,  383,  387,  310,
 /*    50 */    38,    4,   17,   48,
};
#define YY_REDUCE_COUNT (15)
#define YY_REDUCE_MIN   (0)
#define YY_REDUCE_MAX   (363)
static const short yy_reduce_ofst[] = {
 /*     0 */    27,    8,   15,   18,  260,  278,  280,  294,  315,  317,
 /*    10 */   319,  323,  334,  343,  353,  363,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    10 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    20 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    30 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    40 */    88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
 /*    50 */    88,   88,   88,   88,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  LemonParseARG_SDECL                /* A place to hold %extra_argument */
  LemonParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void LemonParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "QUESTION",
  /*    2 */ "BIT_OR",
  /*    3 */ "BIT_AND",
  /*    4 */ "MUL",
  /*    5 */ "DIV",
  /*    6 */ "MOD",
  /*    7 */ "PLUS",
  /*    8 */ "MINUS",
  /*    9 */ "EOL",
  /*   10 */ "COLON",
  /*   11 */ "ASSIGN",
  /*   12 */ "STRING",
  /*   13 */ "COMMA",
  /*   14 */ "IDENTIFIER",
  /*   15 */ "INSTRUCTION",
  /*   16 */ "DIRECTIVE",
  /*   17 */ "BASE",
  /*   18 */ "NUMBER",
  /*   19 */ "SOPEN",
  /*   20 */ "SCLOSE",
  /*   21 */ "OPEN",
  /*   22 */ "CLOSE",
  /*   23 */ "start",
  /*   24 */ "prog",
  /*   25 */ "line",
  /*   26 */ "command",
  /*   27 */ "instr",
  /*   28 */ "args",
  /*   29 */ "strings",
  /*   30 */ "id",
  /*   31 */ "expr",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "start ::= prog",
 /*   1 */ "prog ::= prog line",
 /*   2 */ "prog ::=",
 /*   3 */ "line ::= command EOL",
 /*   4 */ "line ::= EOL",
 /*   5 */ "command ::= instr",
 /*   6 */ "command ::= instr args",
 /*   7 */ "command ::= instr strings",
 /*   8 */ "command ::= id COLON",
 /*   9 */ "command ::= id ASSIGN expr",
 /*  10 */ "strings ::= strings STRING",
 /*  11 */ "strings ::= STRING",
 /*  12 */ "args ::= args COMMA expr",
 /*  13 */ "args ::= expr",
 /*  14 */ "id ::= IDENTIFIER",
 /*  15 */ "id ::= INSTRUCTION",
 /*  16 */ "id ::= DIRECTIVE",
 /*  17 */ "id ::= BASE",
 /*  18 */ "instr ::= INSTRUCTION",
 /*  19 */ "instr ::= DIRECTIVE",
 /*  20 */ "expr ::= NUMBER",
 /*  21 */ "expr ::= id",
 /*  22 */ "expr ::= SOPEN BASE SCLOSE",
 /*  23 */ "expr ::= OPEN expr CLOSE",
 /*  24 */ "expr ::= expr PLUS expr",
 /*  25 */ "expr ::= expr MINUS expr",
 /*  26 */ "expr ::= MINUS expr",
 /*  27 */ "expr ::= expr MUL expr",
 /*  28 */ "expr ::= expr DIV expr",
 /*  29 */ "expr ::= expr MOD expr",
 /*  30 */ "expr ::= id OPEN args CLOSE",
 /*  31 */ "expr ::= id OPEN CLOSE",
 /*  32 */ "expr ::= expr QUESTION expr COLON expr",
 /*  33 */ "expr ::= expr BIT_AND expr",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to LemonParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void LemonParseInit(void *yypRawParser LemonParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  LemonParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to LemonParse and LemonParseFree.
*/
void *LemonParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) LemonParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    LemonParseCTX_STORE
    LemonParseInit(yypParser LemonParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* TERMINAL Destructor */
    case 1: /* QUESTION */
    case 2: /* BIT_OR */
    case 3: /* BIT_AND */
    case 4: /* MUL */
    case 5: /* DIV */
    case 6: /* MOD */
    case 7: /* PLUS */
    case 8: /* MINUS */
    case 9: /* EOL */
    case 10: /* COLON */
    case 11: /* ASSIGN */
    case 12: /* STRING */
    case 13: /* COMMA */
    case 14: /* IDENTIFIER */
    case 15: /* INSTRUCTION */
    case 16: /* DIRECTIVE */
    case 17: /* BASE */
    case 18: /* NUMBER */
    case 19: /* SOPEN */
    case 20: /* SCLOSE */
    case 21: /* OPEN */
    case 22: /* CLOSE */
{
#line 18 "src/triasmParser.y"
 lemonTokenFree((yypminor->yy0)); 
#line 666 "lemon/triasmParser.c"
}
      break;
    case 23: /* start */
{
#line 21 "src/triasmParser.y"
 
#line 673 "lemon/triasmParser.c"
}
      break;
    case 24: /* prog */
{
#line 25 "src/triasmParser.y"
 lemonProgFree((yypminor->yy54)); 
#line 680 "lemon/triasmParser.c"
}
      break;
    case 25: /* line */
    case 26: /* command */
{
#line 30 "src/triasmParser.y"
 lemonCommandFree((yypminor->yy33)); 
#line 688 "lemon/triasmParser.c"
}
      break;
    case 27: /* instr */
    case 29: /* strings */
    case 30: /* id */
{
#line 60 "src/triasmParser.y"
 lemonTokenFree((yypminor->yy19)); 
#line 697 "lemon/triasmParser.c"
}
      break;
    case 28: /* args */
{
#line 48 "src/triasmParser.y"
 lemonArgsFree((yypminor->yy11)); 
#line 704 "lemon/triasmParser.c"
}
      break;
    case 31: /* expr */
{
#line 65 "src/triasmParser.y"
 lemonExprFree((yypminor->yy41)); 
#line 711 "lemon/triasmParser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void LemonParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void LemonParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  LemonParseFinalize(p);
  (*freeProc)(p);
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int LemonParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int LemonParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   LemonParseARG_FETCH
   LemonParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
#line 15 "src/triasmParser.y"
 lemonStackOverflow(lemonState); 
#line 931 "lemon/triasmParser.c"
/******** End %stack_overflow code ********************************************/
   LemonParseARG_STORE /* Suppress warning about unused %extra_argument var */
   LemonParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  LemonParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    23,  /* (0) start ::= prog */
    24,  /* (1) prog ::= prog line */
    24,  /* (2) prog ::= */
    25,  /* (3) line ::= command EOL */
    25,  /* (4) line ::= EOL */
    26,  /* (5) command ::= instr */
    26,  /* (6) command ::= instr args */
    26,  /* (7) command ::= instr strings */
    26,  /* (8) command ::= id COLON */
    26,  /* (9) command ::= id ASSIGN expr */
    29,  /* (10) strings ::= strings STRING */
    29,  /* (11) strings ::= STRING */
    28,  /* (12) args ::= args COMMA expr */
    28,  /* (13) args ::= expr */
    30,  /* (14) id ::= IDENTIFIER */
    30,  /* (15) id ::= INSTRUCTION */
    30,  /* (16) id ::= DIRECTIVE */
    30,  /* (17) id ::= BASE */
    27,  /* (18) instr ::= INSTRUCTION */
    27,  /* (19) instr ::= DIRECTIVE */
    31,  /* (20) expr ::= NUMBER */
    31,  /* (21) expr ::= id */
    31,  /* (22) expr ::= SOPEN BASE SCLOSE */
    31,  /* (23) expr ::= OPEN expr CLOSE */
    31,  /* (24) expr ::= expr PLUS expr */
    31,  /* (25) expr ::= expr MINUS expr */
    31,  /* (26) expr ::= MINUS expr */
    31,  /* (27) expr ::= expr MUL expr */
    31,  /* (28) expr ::= expr DIV expr */
    31,  /* (29) expr ::= expr MOD expr */
    31,  /* (30) expr ::= id OPEN args CLOSE */
    31,  /* (31) expr ::= id OPEN CLOSE */
    31,  /* (32) expr ::= expr QUESTION expr COLON expr */
    31,  /* (33) expr ::= expr BIT_AND expr */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) start ::= prog */
   -2,  /* (1) prog ::= prog line */
    0,  /* (2) prog ::= */
   -2,  /* (3) line ::= command EOL */
   -1,  /* (4) line ::= EOL */
   -1,  /* (5) command ::= instr */
   -2,  /* (6) command ::= instr args */
   -2,  /* (7) command ::= instr strings */
   -2,  /* (8) command ::= id COLON */
   -3,  /* (9) command ::= id ASSIGN expr */
   -2,  /* (10) strings ::= strings STRING */
   -1,  /* (11) strings ::= STRING */
   -3,  /* (12) args ::= args COMMA expr */
   -1,  /* (13) args ::= expr */
   -1,  /* (14) id ::= IDENTIFIER */
   -1,  /* (15) id ::= INSTRUCTION */
   -1,  /* (16) id ::= DIRECTIVE */
   -1,  /* (17) id ::= BASE */
   -1,  /* (18) instr ::= INSTRUCTION */
   -1,  /* (19) instr ::= DIRECTIVE */
   -1,  /* (20) expr ::= NUMBER */
   -1,  /* (21) expr ::= id */
   -3,  /* (22) expr ::= SOPEN BASE SCLOSE */
   -3,  /* (23) expr ::= OPEN expr CLOSE */
   -3,  /* (24) expr ::= expr PLUS expr */
   -3,  /* (25) expr ::= expr MINUS expr */
   -2,  /* (26) expr ::= MINUS expr */
   -3,  /* (27) expr ::= expr MUL expr */
   -3,  /* (28) expr ::= expr DIV expr */
   -3,  /* (29) expr ::= expr MOD expr */
   -4,  /* (30) expr ::= id OPEN args CLOSE */
   -3,  /* (31) expr ::= id OPEN CLOSE */
   -5,  /* (32) expr ::= expr QUESTION expr COLON expr */
   -3,  /* (33) expr ::= expr BIT_AND expr */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  LemonParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  LemonParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  LemonParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* start ::= prog */
#line 22 "src/triasmParser.y"
{ (void)yylhsminor.yy57; lemonResult(yymsp[0].minor.yy54); }
#line 1120 "lemon/triasmParser.c"
  yymsp[0].minor.yy57 = yylhsminor.yy57;
        break;
      case 1: /* prog ::= prog line */
#line 26 "src/triasmParser.y"
{ yylhsminor.yy54 = yymsp[-1].minor.yy54; if (yymsp[0].minor.yy33 != NULL) lemonProgAppend(yymsp[-1].minor.yy54, yymsp[0].minor.yy33); }
#line 1126 "lemon/triasmParser.c"
  yymsp[-1].minor.yy54 = yylhsminor.yy54;
        break;
      case 2: /* prog ::= */
#line 27 "src/triasmParser.y"
{ yymsp[1].minor.yy54 = lemonProgCreate(lemonState); }
#line 1132 "lemon/triasmParser.c"
        break;
      case 3: /* line ::= command EOL */
{  yy_destructor(yypParser,26,&yymsp[-1].minor);
#line 31 "src/triasmParser.y"
{ yymsp[-1].minor.yy33 = A; }
#line 1138 "lemon/triasmParser.c"
  yy_destructor(yypParser,9,&yymsp[0].minor);
}
        break;
      case 4: /* line ::= EOL */
{  yy_destructor(yypParser,9,&yymsp[0].minor);
#line 32 "src/triasmParser.y"
{ yymsp[0].minor.yy33 = NULL; }
#line 1146 "lemon/triasmParser.c"
}
        break;
      case 5: /* command ::= instr */
#line 36 "src/triasmParser.y"
{ yylhsminor.yy33 = lemonInstrCreate(yymsp[0].minor.yy19, NULL, NULL); }
#line 1152 "lemon/triasmParser.c"
  yymsp[0].minor.yy33 = yylhsminor.yy33;
        break;
      case 6: /* command ::= instr args */
#line 37 "src/triasmParser.y"
{ yylhsminor.yy33 = lemonInstrCreate(yymsp[-1].minor.yy19, yymsp[0].minor.yy11, NULL); }
#line 1158 "lemon/triasmParser.c"
  yymsp[-1].minor.yy33 = yylhsminor.yy33;
        break;
      case 7: /* command ::= instr strings */
#line 38 "src/triasmParser.y"
{ yylhsminor.yy33 = lemonInstrCreate(yymsp[-1].minor.yy19, NULL, yymsp[0].minor.yy19); }
#line 1164 "lemon/triasmParser.c"
  yymsp[-1].minor.yy33 = yylhsminor.yy33;
        break;
      case 8: /* command ::= id COLON */
#line 39 "src/triasmParser.y"
{ yylhsminor.yy33 = lemonLabelCreate(yymsp[-1].minor.yy19); }
#line 1170 "lemon/triasmParser.c"
  yy_destructor(yypParser,10,&yymsp[0].minor);
  yymsp[-1].minor.yy33 = yylhsminor.yy33;
        break;
      case 9: /* command ::= id ASSIGN expr */
#line 40 "src/triasmParser.y"
{ yylhsminor.yy33 = lemonAssignCreate(yymsp[-2].minor.yy19, yymsp[0].minor.yy41); }
#line 1177 "lemon/triasmParser.c"
  yy_destructor(yypParser,11,&yymsp[-1].minor);
  yymsp[-2].minor.yy33 = yylhsminor.yy33;
        break;
      case 10: /* strings ::= strings STRING */
#line 44 "src/triasmParser.y"
{ yylhsminor.yy19 = yymsp[-1].minor.yy19; lemonStringAppend(yymsp[-1].minor.yy19, yymsp[0].minor.yy0); }
#line 1184 "lemon/triasmParser.c"
  yymsp[-1].minor.yy19 = yylhsminor.yy19;
        break;
      case 11: /* strings ::= STRING */
      case 14: /* id ::= IDENTIFIER */ yytestcase(yyruleno==14);
      case 15: /* id ::= INSTRUCTION */ yytestcase(yyruleno==15);
      case 16: /* id ::= DIRECTIVE */ yytestcase(yyruleno==16);
      case 17: /* id ::= BASE */ yytestcase(yyruleno==17);
      case 18: /* instr ::= INSTRUCTION */ yytestcase(yyruleno==18);
      case 19: /* instr ::= DIRECTIVE */ yytestcase(yyruleno==19);
#line 45 "src/triasmParser.y"
{ yylhsminor.yy19 = yymsp[0].minor.yy0; }
#line 1196 "lemon/triasmParser.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 12: /* args ::= args COMMA expr */
#line 49 "src/triasmParser.y"
{ yylhsminor.yy11 = yymsp[-2].minor.yy11; lemonArgsAppend(yymsp[-2].minor.yy11, yymsp[0].minor.yy41); }
#line 1202 "lemon/triasmParser.c"
  yy_destructor(yypParser,13,&yymsp[-1].minor);
  yymsp[-2].minor.yy11 = yylhsminor.yy11;
        break;
      case 13: /* args ::= expr */
#line 50 "src/triasmParser.y"
{ yylhsminor.yy11 = lemonArgsCreate(lemonState); lemonArgsAppend(yylhsminor.yy11, yymsp[0].minor.yy41); }
#line 1209 "lemon/triasmParser.c"
  yymsp[0].minor.yy11 = yylhsminor.yy11;
        break;
      case 20: /* expr ::= NUMBER */
#line 66 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprNumber(yymsp[0].minor.yy0); }
#line 1215 "lemon/triasmParser.c"
  yymsp[0].minor.yy41 = yylhsminor.yy41;
        break;
      case 21: /* expr ::= id */
#line 67 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprIdentifier(yymsp[0].minor.yy19); }
#line 1221 "lemon/triasmParser.c"
  yymsp[0].minor.yy41 = yylhsminor.yy41;
        break;
      case 22: /* expr ::= SOPEN BASE SCLOSE */
{  yy_destructor(yypParser,19,&yymsp[-2].minor);
#line 68 "src/triasmParser.y"
{ yymsp[-2].minor.yy41 = lemonExprBase(yymsp[-1].minor.yy0); }
#line 1228 "lemon/triasmParser.c"
  yy_destructor(yypParser,20,&yymsp[0].minor);
}
        break;
      case 23: /* expr ::= OPEN expr CLOSE */
{  yy_destructor(yypParser,21,&yymsp[-2].minor);
#line 69 "src/triasmParser.y"
{ yymsp[-2].minor.yy41 = yymsp[-1].minor.yy41; }
#line 1236 "lemon/triasmParser.c"
  yy_destructor(yypParser,22,&yymsp[0].minor);
}
        break;
      case 24: /* expr ::= expr PLUS expr */
#line 70 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('+', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1243 "lemon/triasmParser.c"
  yy_destructor(yypParser,7,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 25: /* expr ::= expr MINUS expr */
#line 71 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('-', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1250 "lemon/triasmParser.c"
  yy_destructor(yypParser,8,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 26: /* expr ::= MINUS expr */
{  yy_destructor(yypParser,8,&yymsp[-1].minor);
#line 72 "src/triasmParser.y"
{ yymsp[-1].minor.yy41 = lemonExprUnOp('-', yymsp[0].minor.yy41); }
#line 1258 "lemon/triasmParser.c"
}
        break;
      case 27: /* expr ::= expr MUL expr */
#line 73 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('*', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1264 "lemon/triasmParser.c"
  yy_destructor(yypParser,4,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 28: /* expr ::= expr DIV expr */
#line 74 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('/', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1271 "lemon/triasmParser.c"
  yy_destructor(yypParser,5,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 29: /* expr ::= expr MOD expr */
#line 75 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('%', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1278 "lemon/triasmParser.c"
  yy_destructor(yypParser,6,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 30: /* expr ::= id OPEN args CLOSE */
#line 76 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprCall(yymsp[-3].minor.yy19, yymsp[-1].minor.yy11); }
#line 1285 "lemon/triasmParser.c"
  yy_destructor(yypParser,21,&yymsp[-2].minor);
  yy_destructor(yypParser,22,&yymsp[0].minor);
  yymsp[-3].minor.yy41 = yylhsminor.yy41;
        break;
      case 31: /* expr ::= id OPEN CLOSE */
#line 77 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprCall(yymsp[-2].minor.yy19, lemonArgsCreate(lemonState)); }
#line 1293 "lemon/triasmParser.c"
  yy_destructor(yypParser,21,&yymsp[-1].minor);
  yy_destructor(yypParser,22,&yymsp[0].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      case 32: /* expr ::= expr QUESTION expr COLON expr */
#line 78 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprTriOp(yymsp[-4].minor.yy41, yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1301 "lemon/triasmParser.c"
  yy_destructor(yypParser,1,&yymsp[-3].minor);
  yy_destructor(yypParser,10,&yymsp[-1].minor);
  yymsp[-4].minor.yy41 = yylhsminor.yy41;
        break;
      case 33: /* expr ::= expr BIT_AND expr */
#line 79 "src/triasmParser.y"
{ yylhsminor.yy41 = lemonExprBinOp('&', yymsp[-2].minor.yy41, yymsp[0].minor.yy41); }
#line 1309 "lemon/triasmParser.c"
  yy_destructor(yypParser,3,&yymsp[-1].minor);
  yymsp[-2].minor.yy41 = yylhsminor.yy41;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 16 "src/triasmParser.y"
 lemonFailure(lemonState); 
#line 1357 "lemon/triasmParser.c"
/************ End %parse_failure code *****************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  LemonParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 14 "src/triasmParser.y"
 lemonError(TOKEN); 
#line 1378 "lemon/triasmParser.c"
/************ End %syntax_error code ******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "LemonParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void LemonParse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  LemonParseTOKENTYPE yyminor       /* The value for the token */
  LemonParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  LemonParseCTX_FETCH
  LemonParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor LemonParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int LemonParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
