/* This file is automatically generated by Lemon from input grammar
** source file "src/triasmParser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 6 "src/triasmParser.y"
 #include "triasmParser.h" 
#line 31 "lemon/triasmParser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LEMON_EOL
#define LEMON_EOL                             1
#define LEMON_INSTRUCTION                     2
#define LEMON_COLON                           3
#define LEMON_ASSIGN                          4
#define LEMON_STRING                          5
#define LEMON_COMMA                           6
#define LEMON_IDENTIFIER                      7
#define LEMON_BASE                            8
#define LEMON_QUESTION                        9
#define LEMON_OR                             10
#define LEMON_AND                            11
#define LEMON_BIT_OR                         12
#define LEMON_BIT_XOR                        13
#define LEMON_BIT_AND                        14
#define LEMON_EQ                             15
#define LEMON_NE                             16
#define LEMON_LT                             17
#define LEMON_GT                             18
#define LEMON_LE                             19
#define LEMON_GE                             20
#define LEMON_SHL                            21
#define LEMON_SHR                            22
#define LEMON_PLUS                           23
#define LEMON_MINUS                          24
#define LEMON_MUL                            25
#define LEMON_DIV                            26
#define LEMON_MOD                            27
#define LEMON_NOT                            28
#define LEMON_BIT_NOT                        29
#define LEMON_OPEN                           30
#define LEMON_CLOSE                          31
#define LEMON_DECIMAL                        32
#define LEMON_HEX                            33
#define LEMON_OCT                            34
#define LEMON_SOPEN                          35
#define LEMON_SCLOSE                         36
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    LemonParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is LemonParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    LemonParseARG_SDECL     A static variable declaration for the %extra_argument
**    LemonParseARG_PDECL     A parameter declaration for the %extra_argument
**    LemonParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    LemonParseARG_STORE     Code to store %extra_argument into yypParser
**    LemonParseARG_FETCH     Code to extract %extra_argument from yypParser
**    LemonParseCTX_*         As LemonParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 46
#define YYACTIONTYPE unsigned char
#define LemonParseTOKENTYPE  const char* 
typedef union {
  int yyinit;
  LemonParseTOKENTYPE yy0;
  LemonCommand* yy1;
  LemonProg* yy30;
  LemonExpr* yy45;
  LemonArgs* yy47;
  const char* yy76;
  void* yy81;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 2000
#endif
#define LemonParseARG_SDECL
#define LemonParseARG_PDECL
#define LemonParseARG_PARAM
#define LemonParseARG_FETCH
#define LemonParseARG_STORE
#define LemonParseCTX_SDECL  Lemon* th ;
#define LemonParseCTX_PDECL , Lemon* th 
#define LemonParseCTX_PARAM ,th 
#define LemonParseCTX_FETCH  Lemon* th =yypParser->th ;
#define LemonParseCTX_STORE yypParser->th =th ;
#define YYNSTATE             84
#define YYNRULE              50
#define YYNRULE_WITH_ACTION  50
#define YYNTOKEN             37
#define YY_MAX_SHIFT         83
#define YY_MIN_SHIFTREDUCE   84
#define YY_MAX_SHIFTREDUCE   133
#define YY_ERROR_ACTION      134
#define YY_ACCEPT_ACTION     135
#define YY_NO_ACTION         136
#define YY_MIN_REDUCE        137
#define YY_MAX_REDUCE        186
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (1198)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   136,  155,  136,  155,  155,  145,  155,  135,    3,  155,
 /*    10 */   155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
 /*    20 */   155,  155,  155,  155,  155,  155,  155,  155,   33,   66,
 /*    30 */   155,  155,  153,   79,  153,  153,   42,  153,   33,   67,
 /*    40 */   153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
 /*    50 */   153,  153,  153,  153,  153,  153,  153,  153,  153,   33,
 /*    60 */    68,  153,  153,  185,   36,  185,   72,   83,  185,  143,
 /*    70 */    74,  185,  185,  185,  185,  185,  185,  185,  185,  185,
 /*    80 */   185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
 /*    90 */    33,   43,    2,  185,  156,  149,  156,   33,   44,  156,
 /*   100 */     4,   71,  156,   28,   27,   26,   25,   24,   23,   22,
 /*   110 */    21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
 /*   120 */    11,  154,  136,  154,  156,  149,  154,   33,   45,  154,
 /*   130 */   154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
 /*   140 */   154,  154,  154,  154,  154,  154,  154,  154,   33,   46,
 /*   150 */   154,  154,  186,  136,  186,   33,   47,  186,   33,   48,
 /*   160 */   186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
 /*   170 */   186,  186,  186,  186,  186,  186,  186,  186,  186,  184,
 /*   180 */   136,  184,  186,  136,  184,   33,   49,  184,  184,  184,
 /*   190 */   184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
 /*   200 */   184,  184,  184,  184,  184,  184,  183,  136,  183,  184,
 /*   210 */   136,  183,   33,   50,  183,  183,  183,  183,  183,  183,
 /*   220 */   183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
 /*   230 */   183,  183,  183,  182,  136,  182,  183,  136,  182,   33,
 /*   240 */    51,  182,  182,  182,  182,  182,  182,  182,  182,  182,
 /*   250 */   182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
 /*   260 */   181,  136,  181,  182,  136,  181,   33,   52,  181,  181,
 /*   270 */   181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
 /*   280 */   181,  181,  181,  181,  181,  181,  181,  180,  136,  180,
 /*   290 */   181,  136,  180,   33,   53,  180,  180,  180,  180,  180,
 /*   300 */   180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
 /*   310 */   180,  180,  180,  180,  179,  136,  179,  180,  136,  179,
 /*   320 */    33,   54,  179,  179,  179,  179,  179,  179,  179,  179,
 /*   330 */   179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
 /*   340 */   179,  178,  136,  178,  179,  136,  178,   33,   55,  178,
 /*   350 */   178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
 /*   360 */   178,  178,  178,  178,  178,  178,  178,  178,  177,  136,
 /*   370 */   177,  178,  136,  177,   33,   56,  177,  177,  177,  177,
 /*   380 */   177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
 /*   390 */   177,  177,  177,  177,  177,  176,  136,  176,  177,  136,
 /*   400 */   176,   33,   57,  176,  176,  176,  176,  176,  176,  176,
 /*   410 */   176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
 /*   420 */   176,  176,  175,  136,  175,  176,  136,  175,   33,   58,
 /*   430 */   175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
 /*   440 */   175,  175,  175,  175,  175,  175,  175,  175,  175,  174,
 /*   450 */   136,  174,  175,  136,  174,   33,   59,  174,  174,  174,
 /*   460 */   174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
 /*   470 */   174,  174,  174,  174,  174,  174,  173,  136,  173,  174,
 /*   480 */   136,  173,   33,   60,  173,  173,  173,  173,  173,  173,
 /*   490 */   173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
 /*   500 */   173,  173,  173,  172,  136,  172,  173,  136,  172,   33,
 /*   510 */    61,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*   520 */   172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*   530 */   171,  136,  171,  172,  136,  171,   33,   62,  171,  171,
 /*   540 */   171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
 /*   550 */   171,  171,  171,  171,   13,   12,   11,  170,  136,  170,
 /*   560 */   171,  136,  170,   33,   63,  170,  170,  170,  170,  170,
 /*   570 */   170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
 /*   580 */   170,   13,   12,   11,  169,  136,  169,  170,  136,  169,
 /*   590 */    33,   64,  169,  169,  169,  169,  169,  169,  169,  169,
 /*   600 */   169,  169,  169,  169,  169,  169,   15,   14,   13,   12,
 /*   610 */    11,  168,  136,  168,  169,  136,  168,   33,   34,  168,
 /*   620 */   168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
 /*   630 */   168,  168,  168,   15,   14,   13,   12,   11,  167,  136,
 /*   640 */   167,  168,  136,  167,   33,   69,  167,  167,  167,  167,
 /*   650 */   167,  167,  167,  167,  167,  167,  167,  167,   17,   16,
 /*   660 */    15,   14,   13,   12,   11,  166,  136,  166,  167,  136,
 /*   670 */   166,   78,    5,  166,  166,  166,  166,  166,  166,  166,
 /*   680 */   166,  166,  166,  166,  166,   17,   16,   15,   14,   13,
 /*   690 */    12,   11,  165,  136,  165,  166,  136,  165,  136,  136,
 /*   700 */   165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
 /*   710 */   165,  165,   17,   16,   15,   14,   13,   12,   11,  164,
 /*   720 */   136,  164,  165,  136,  164,  136,  136,  164,  164,  164,
 /*   730 */   164,  164,  164,  164,  164,  164,  164,  164,  164,   17,
 /*   740 */    16,   15,   14,   13,   12,   11,  163,  136,  163,  164,
 /*   750 */   136,  163,  136,  136,  163,  163,  163,  163,  163,  163,
 /*   760 */   163,  163,   21,   20,   19,   18,   17,   16,   15,   14,
 /*   770 */    13,   12,   11,  162,  136,  162,  163,  136,  162,  136,
 /*   780 */   136,  162,  162,  162,  162,  162,  162,  162,  162,   21,
 /*   790 */    20,   19,   18,   17,   16,   15,   14,   13,   12,   11,
 /*   800 */   161,  136,  161,  162,  136,  161,  136,  136,  161,  161,
 /*   810 */   161,  161,  161,  161,   23,   22,   21,   20,   19,   18,
 /*   820 */    17,   16,   15,   14,   13,   12,   11,  160,  136,  160,
 /*   830 */   161,  136,  160,  136,  136,  160,  160,  160,  160,  160,
 /*   840 */    24,   23,   22,   21,   20,   19,   18,   17,   16,   15,
 /*   850 */    14,   13,   12,   11,  159,  136,  159,  160,  136,  159,
 /*   860 */   136,  136,  159,  159,  159,  159,   25,   24,   23,   22,
 /*   870 */    21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
 /*   880 */    11,  158,  136,  158,  159,  136,  158,  136,  136,  158,
 /*   890 */   158,  158,   26,   25,   24,   23,   22,   21,   20,   19,
 /*   900 */    18,   17,   16,   15,   14,   13,   12,   11,  157,  136,
 /*   910 */   157,  158,  136,  157,  136,  136,  157,  157,   27,   26,
 /*   920 */    25,   24,   23,   22,   21,   20,   19,   18,   17,   16,
 /*   930 */    15,   14,   13,   12,   11,  152,  136,  148,  157,  136,
 /*   940 */   152,  148,  136,   30,   28,   27,   26,   25,   24,   23,
 /*   950 */    22,   21,   20,   19,   18,   17,   16,   15,   14,   13,
 /*   960 */    12,   11,  151,  136,  147,  152,  136,  151,  147,  136,
 /*   970 */    30,   28,   27,   26,   25,   24,   23,   22,   21,   20,
 /*   980 */    19,   18,   17,   16,   15,   14,   13,   12,   11,  146,
 /*   990 */   136,   81,  151,   33,   65,   73,  136,   30,   28,   27,
 /*  1000 */    26,   25,   24,   23,   22,   21,   20,   19,   18,   17,
 /*  1010 */    16,   15,   14,   13,   12,   11,   30,   28,   27,   26,
 /*  1020 */    25,   24,   23,   22,   21,   20,   19,   18,   17,   16,
 /*  1030 */    15,   14,   13,   12,   11,   29,  144,  136,   40,  136,
 /*  1040 */    76,   30,   28,   27,   26,   25,   24,   23,   22,   21,
 /*  1050 */    20,   19,   18,   17,   16,   15,   14,   13,   12,   11,
 /*  1060 */   142,   35,  154,  154,   75,  136,   32,   31,  139,  139,
 /*  1070 */   139,  136,  136,  136,  136,  139,  139,   82,   77,   33,
 /*  1080 */    65,   73,   10,    9,  136,  136,  136,    8,    7,    6,
 /*  1090 */   136,   39,   38,   37,   80,  150,   35,  137,   70,    1,
 /*  1100 */   136,   32,   31,  136,   32,   31,  141,  141,  141,  136,
 /*  1110 */   136,  136,  136,  141,  141,  136,  136,   10,    9,  136,
 /*  1120 */   136,  136,    8,    7,    6,  150,   39,   38,   37,   80,
 /*  1130 */    35,  140,  140,  140,  136,   32,   31,  136,  140,  140,
 /*  1140 */   138,  138,  138,  136,  136,  136,  136,  138,  138,  136,
 /*  1150 */   136,   10,    9,  136,  136,  136,    8,    7,    6,   41,
 /*  1160 */    39,   38,   37,   80,   35,  136,  136,  136,  136,   32,
 /*  1170 */    31,  136,  136,  136,  136,  136,  136,  136,  136,  136,
 /*  1180 */   136,  136,  136,  136,  136,   10,    9,  136,  136,  136,
 /*  1190 */     8,    7,    6,  136,   39,   38,   37,   80,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    46,    1,   46,    3,    4,    1,    6,   37,   38,    9,
 /*    10 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*    20 */    20,   21,   22,   23,   24,   25,   26,   27,   43,   44,
 /*    30 */    30,   31,    1,    8,    3,    4,   31,    6,   43,   44,
 /*    40 */     9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
 /*    50 */    19,   20,   21,   22,   23,   24,   25,   26,   27,   43,
 /*    60 */    44,   30,   31,    1,   36,    3,   39,   40,    6,    1,
 /*    70 */    43,    9,   10,   11,   12,   13,   14,   15,   16,   17,
 /*    80 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*    90 */    43,   44,   30,   31,    1,    1,    3,   43,   44,    6,
 /*   100 */     6,    1,    9,   10,   11,   12,   13,   14,   15,   16,
 /*   110 */    17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
 /*   120 */    27,    1,   46,    3,   31,   31,    6,   43,   44,    9,
 /*   130 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   140 */    20,   21,   22,   23,   24,   25,   26,   27,   43,   44,
 /*   150 */    30,   31,    1,   46,    3,   43,   44,    6,   43,   44,
 /*   160 */     9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
 /*   170 */    19,   20,   21,   22,   23,   24,   25,   26,   27,    1,
 /*   180 */    46,    3,   31,   46,    6,   43,   44,    9,   10,   11,
 /*   190 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   200 */    22,   23,   24,   25,   26,   27,    1,   46,    3,   31,
 /*   210 */    46,    6,   43,   44,    9,   10,   11,   12,   13,   14,
 /*   220 */    15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
 /*   230 */    25,   26,   27,    1,   46,    3,   31,   46,    6,   43,
 /*   240 */    44,    9,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   250 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   260 */     1,   46,    3,   31,   46,    6,   43,   44,    9,   10,
 /*   270 */    11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*   280 */    21,   22,   23,   24,   25,   26,   27,    1,   46,    3,
 /*   290 */    31,   46,    6,   43,   44,    9,   10,   11,   12,   13,
 /*   300 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   310 */    24,   25,   26,   27,    1,   46,    3,   31,   46,    6,
 /*   320 */    43,   44,    9,   10,   11,   12,   13,   14,   15,   16,
 /*   330 */    17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
 /*   340 */    27,    1,   46,    3,   31,   46,    6,   43,   44,    9,
 /*   350 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   360 */    20,   21,   22,   23,   24,   25,   26,   27,    1,   46,
 /*   370 */     3,   31,   46,    6,   43,   44,    9,   10,   11,   12,
 /*   380 */    13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
 /*   390 */    23,   24,   25,   26,   27,    1,   46,    3,   31,   46,
 /*   400 */     6,   43,   44,    9,   10,   11,   12,   13,   14,   15,
 /*   410 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   420 */    26,   27,    1,   46,    3,   31,   46,    6,   43,   44,
 /*   430 */     9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
 /*   440 */    19,   20,   21,   22,   23,   24,   25,   26,   27,    1,
 /*   450 */    46,    3,   31,   46,    6,   43,   44,    9,   10,   11,
 /*   460 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   470 */    22,   23,   24,   25,   26,   27,    1,   46,    3,   31,
 /*   480 */    46,    6,   43,   44,    9,   10,   11,   12,   13,   14,
 /*   490 */    15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
 /*   500 */    25,   26,   27,    1,   46,    3,   31,   46,    6,   43,
 /*   510 */    44,    9,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   520 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   530 */     1,   46,    3,   31,   46,    6,   43,   44,    9,   10,
 /*   540 */    11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*   550 */    21,   22,   23,   24,   25,   26,   27,    1,   46,    3,
 /*   560 */    31,   46,    6,   43,   44,    9,   10,   11,   12,   13,
 /*   570 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   580 */    24,   25,   26,   27,    1,   46,    3,   31,   46,    6,
 /*   590 */    43,   44,    9,   10,   11,   12,   13,   14,   15,   16,
 /*   600 */    17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
 /*   610 */    27,    1,   46,    3,   31,   46,    6,   43,   44,    9,
 /*   620 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   630 */    20,   21,   22,   23,   24,   25,   26,   27,    1,   46,
 /*   640 */     3,   31,   46,    6,   43,   44,    9,   10,   11,   12,
 /*   650 */    13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
 /*   660 */    23,   24,   25,   26,   27,    1,   46,    3,   31,   46,
 /*   670 */     6,    3,    4,    9,   10,   11,   12,   13,   14,   15,
 /*   680 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   690 */    26,   27,    1,   46,    3,   31,   46,    6,   46,   46,
 /*   700 */     9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
 /*   710 */    19,   20,   21,   22,   23,   24,   25,   26,   27,    1,
 /*   720 */    46,    3,   31,   46,    6,   46,   46,    9,   10,   11,
 /*   730 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*   740 */    22,   23,   24,   25,   26,   27,    1,   46,    3,   31,
 /*   750 */    46,    6,   46,   46,    9,   10,   11,   12,   13,   14,
 /*   760 */    15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
 /*   770 */    25,   26,   27,    1,   46,    3,   31,   46,    6,   46,
 /*   780 */    46,    9,   10,   11,   12,   13,   14,   15,   16,   17,
 /*   790 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*   800 */     1,   46,    3,   31,   46,    6,   46,   46,    9,   10,
 /*   810 */    11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*   820 */    21,   22,   23,   24,   25,   26,   27,    1,   46,    3,
 /*   830 */    31,   46,    6,   46,   46,    9,   10,   11,   12,   13,
 /*   840 */    14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
 /*   850 */    24,   25,   26,   27,    1,   46,    3,   31,   46,    6,
 /*   860 */    46,   46,    9,   10,   11,   12,   13,   14,   15,   16,
 /*   870 */    17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
 /*   880 */    27,    1,   46,    3,   31,   46,    6,   46,   46,    9,
 /*   890 */    10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*   900 */    20,   21,   22,   23,   24,   25,   26,   27,    1,   46,
 /*   910 */     3,   31,   46,    6,   46,   46,    9,   10,   11,   12,
 /*   920 */    13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
 /*   930 */    23,   24,   25,   26,   27,    1,   46,    1,   31,   46,
 /*   940 */     6,    5,   46,    9,   10,   11,   12,   13,   14,   15,
 /*   950 */    16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
 /*   960 */    26,   27,    1,   46,    1,   31,   46,    6,    5,   46,
 /*   970 */     9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
 /*   980 */    19,   20,   21,   22,   23,   24,   25,   26,   27,    1,
 /*   990 */    46,   41,   31,   43,   44,   45,   46,    9,   10,   11,
 /*  1000 */    12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
 /*  1010 */    22,   23,   24,   25,   26,   27,    9,   10,   11,   12,
 /*  1020 */    13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
 /*  1030 */    23,   24,   25,   26,   27,    3,    1,   46,   31,   46,
 /*  1040 */     5,    9,   10,   11,   12,   13,   14,   15,   16,   17,
 /*  1050 */    18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
 /*  1060 */     1,    2,    3,    4,    5,   46,    7,    8,    0,    1,
 /*  1070 */     2,   46,   46,   46,   46,    7,    8,   41,   42,   43,
 /*  1080 */    44,   45,   23,   24,   46,   46,   46,   28,   29,   30,
 /*  1090 */    46,   32,   33,   34,   35,    1,    2,    0,    1,    2,
 /*  1100 */    46,    7,    8,   46,    7,    8,    0,    1,    2,   46,
 /*  1110 */    46,   46,   46,    7,    8,   46,   46,   23,   24,   46,
 /*  1120 */    46,   46,   28,   29,   30,   31,   32,   33,   34,   35,
 /*  1130 */     2,    0,    1,    2,   46,    7,    8,   46,    7,    8,
 /*  1140 */     0,    1,    2,   46,   46,   46,   46,    7,    8,   46,
 /*  1150 */    46,   23,   24,   46,   46,   46,   28,   29,   30,   31,
 /*  1160 */    32,   33,   34,   35,    2,   46,   46,   46,   46,    7,
 /*  1170 */     8,   46,   46,   46,   46,   46,   46,   46,   46,   46,
 /*  1180 */    46,   46,   46,   46,   46,   23,   24,   46,   46,   46,
 /*  1190 */    28,   29,   30,   46,   32,   33,   34,   35,   46,   46,
 /*  1200 */    46,   46,   37,   37,   37,   37,   37,   37,   37,   37,
 /*  1210 */    37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
 /*  1220 */    37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
 /*  1230 */    37,   37,   37,   37,   37,
};
#define YY_SHIFT_COUNT    (83)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (1162)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */  1068, 1059, 1128, 1097, 1094, 1162, 1162, 1162, 1162, 1162,
 /*    10 */  1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162,
 /*    20 */  1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162, 1162,
 /*    30 */  1162,    0,   31,   62,   93,  120,  151,  178,  205,  232,
 /*    40 */   259,  286,  313,  340,  367,  394,  421,  448,  475,  502,
 /*    50 */   529,  556,  583,  610,  637,  664,  691,  718,  745,  772,
 /*    60 */   799,  826,  853,  880,  907,  934,  961,  988, 1007, 1032,
 /*    70 */  1106, 1131, 1140,   94,  668,  936,  963, 1035,    4,   28,
 /*    80 */    25,    5,   68,  100,
};
#define YY_REDUCE_COUNT (30)
#define YY_REDUCE_MIN   (-30)
#define YY_REDUCE_MAX   (1036)
static const short yy_reduce_ofst[] = {
 /*     0 */   -30, 1036,  950,   27,  -15,   -5,   16,   47,   54,   84,
 /*    10 */   105,  112,  115,  142,  169,  196,  223,  250,  277,  304,
 /*    20 */   331,  358,  385,  412,  439,  466,  493,  520,  547,  574,
 /*    30 */   601,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    10 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    20 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    30 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    40 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    50 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    60 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    70 */   134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
 /*    80 */   134,  134,  134,  134,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  LemonParseARG_SDECL                /* A place to hold %extra_argument */
  LemonParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void LemonParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "EOL",
  /*    2 */ "INSTRUCTION",
  /*    3 */ "COLON",
  /*    4 */ "ASSIGN",
  /*    5 */ "STRING",
  /*    6 */ "COMMA",
  /*    7 */ "IDENTIFIER",
  /*    8 */ "BASE",
  /*    9 */ "QUESTION",
  /*   10 */ "OR",
  /*   11 */ "AND",
  /*   12 */ "BIT_OR",
  /*   13 */ "BIT_XOR",
  /*   14 */ "BIT_AND",
  /*   15 */ "EQ",
  /*   16 */ "NE",
  /*   17 */ "LT",
  /*   18 */ "GT",
  /*   19 */ "LE",
  /*   20 */ "GE",
  /*   21 */ "SHL",
  /*   22 */ "SHR",
  /*   23 */ "PLUS",
  /*   24 */ "MINUS",
  /*   25 */ "MUL",
  /*   26 */ "DIV",
  /*   27 */ "MOD",
  /*   28 */ "NOT",
  /*   29 */ "BIT_NOT",
  /*   30 */ "OPEN",
  /*   31 */ "CLOSE",
  /*   32 */ "DECIMAL",
  /*   33 */ "HEX",
  /*   34 */ "OCT",
  /*   35 */ "SOPEN",
  /*   36 */ "SCLOSE",
  /*   37 */ "root",
  /*   38 */ "prog",
  /*   39 */ "line",
  /*   40 */ "command",
  /*   41 */ "args",
  /*   42 */ "strings",
  /*   43 */ "id",
  /*   44 */ "expr",
  /*   45 */ "argsnc",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "root ::= prog",
 /*   1 */ "prog ::= prog line",
 /*   2 */ "prog ::=",
 /*   3 */ "line ::= command EOL",
 /*   4 */ "line ::= EOL",
 /*   5 */ "command ::= INSTRUCTION",
 /*   6 */ "command ::= INSTRUCTION args",
 /*   7 */ "command ::= INSTRUCTION strings",
 /*   8 */ "command ::= id COLON",
 /*   9 */ "command ::= id ASSIGN expr",
 /*  10 */ "strings ::= strings STRING",
 /*  11 */ "strings ::= STRING",
 /*  12 */ "args ::= argsnc",
 /*  13 */ "args ::= argsnc COMMA",
 /*  14 */ "argsnc ::= argsnc COMMA expr",
 /*  15 */ "argsnc ::= expr",
 /*  16 */ "id ::= IDENTIFIER",
 /*  17 */ "id ::= INSTRUCTION",
 /*  18 */ "id ::= BASE",
 /*  19 */ "expr ::= expr QUESTION expr COLON expr",
 /*  20 */ "expr ::= expr OR expr",
 /*  21 */ "expr ::= expr AND expr",
 /*  22 */ "expr ::= expr BIT_OR expr",
 /*  23 */ "expr ::= expr BIT_XOR expr",
 /*  24 */ "expr ::= expr BIT_AND expr",
 /*  25 */ "expr ::= expr EQ expr",
 /*  26 */ "expr ::= expr NE expr",
 /*  27 */ "expr ::= expr LT expr",
 /*  28 */ "expr ::= expr GT expr",
 /*  29 */ "expr ::= expr LE expr",
 /*  30 */ "expr ::= expr GE expr",
 /*  31 */ "expr ::= expr SHL expr",
 /*  32 */ "expr ::= expr SHR expr",
 /*  33 */ "expr ::= expr PLUS expr",
 /*  34 */ "expr ::= expr MINUS expr",
 /*  35 */ "expr ::= expr MUL expr",
 /*  36 */ "expr ::= expr DIV expr",
 /*  37 */ "expr ::= expr MOD expr",
 /*  38 */ "expr ::= PLUS expr",
 /*  39 */ "expr ::= MINUS expr",
 /*  40 */ "expr ::= NOT expr",
 /*  41 */ "expr ::= BIT_NOT expr",
 /*  42 */ "expr ::= id OPEN args CLOSE",
 /*  43 */ "expr ::= id OPEN CLOSE",
 /*  44 */ "expr ::= OPEN expr CLOSE",
 /*  45 */ "expr ::= DECIMAL",
 /*  46 */ "expr ::= HEX",
 /*  47 */ "expr ::= OCT",
 /*  48 */ "expr ::= id",
 /*  49 */ "expr ::= SOPEN BASE SCLOSE",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to LemonParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void LemonParseInit(void *yypRawParser LemonParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  LemonParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to LemonParse and LemonParseFree.
*/
void *LemonParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) LemonParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    LemonParseCTX_STORE
    LemonParseInit(yypParser LemonParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* TERMINAL Destructor */
    case 1: /* EOL */
    case 2: /* INSTRUCTION */
    case 3: /* COLON */
    case 4: /* ASSIGN */
    case 5: /* STRING */
    case 6: /* COMMA */
    case 7: /* IDENTIFIER */
    case 8: /* BASE */
    case 9: /* QUESTION */
    case 10: /* OR */
    case 11: /* AND */
    case 12: /* BIT_OR */
    case 13: /* BIT_XOR */
    case 14: /* BIT_AND */
    case 15: /* EQ */
    case 16: /* NE */
    case 17: /* LT */
    case 18: /* GT */
    case 19: /* LE */
    case 20: /* GE */
    case 21: /* SHL */
    case 22: /* SHR */
    case 23: /* PLUS */
    case 24: /* MINUS */
    case 25: /* MUL */
    case 26: /* DIV */
    case 27: /* MOD */
    case 28: /* NOT */
    case 29: /* BIT_NOT */
    case 30: /* OPEN */
    case 31: /* CLOSE */
    case 32: /* DECIMAL */
    case 33: /* HEX */
    case 34: /* OCT */
    case 35: /* SOPEN */
    case 36: /* SCLOSE */
{
#line 12 "src/triasmParser.y"
 lemonTokenFree(th, (yypminor->yy0)); 
#line 891 "lemon/triasmParser.c"
}
      break;
    case 37: /* root */
{
#line 16 "src/triasmParser.y"
 
#line 898 "lemon/triasmParser.c"
}
      break;
    case 38: /* prog */
{
#line 21 "src/triasmParser.y"
 lemonProgFree(th, (yypminor->yy30)); 
#line 905 "lemon/triasmParser.c"
}
      break;
    case 39: /* line */
    case 40: /* command */
{
#line 27 "src/triasmParser.y"
 lemonCommandFree(th, (yypminor->yy1)); 
#line 913 "lemon/triasmParser.c"
}
      break;
    case 41: /* args */
    case 45: /* argsnc */
{
#line 48 "src/triasmParser.y"
 lemonArgsFree(th, (yypminor->yy47)); 
#line 921 "lemon/triasmParser.c"
}
      break;
    case 42: /* strings */
    case 43: /* id */
{
#line 42 "src/triasmParser.y"
 lemonTokenFree(th, (yypminor->yy76)); 
#line 929 "lemon/triasmParser.c"
}
      break;
    case 44: /* expr */
{
#line 65 "src/triasmParser.y"
 lemonExprFree(th, (yypminor->yy45)); 
#line 936 "lemon/triasmParser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void LemonParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef LemonParse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void LemonParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  LemonParseFinalize(p);
  (*freeProc)(p);
}
#endif /* LemonParse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int LemonParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int LemonParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   LemonParseARG_FETCH
   LemonParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
#line 9 "src/triasmParser.y"
 lemonStackOverflow(th); 
#line 1156 "lemon/triasmParser.c"
/******** End %stack_overflow code ********************************************/
   LemonParseARG_STORE /* Suppress warning about unused %extra_argument var */
   LemonParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  LemonParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    37,  /* (0) root ::= prog */
    38,  /* (1) prog ::= prog line */
    38,  /* (2) prog ::= */
    39,  /* (3) line ::= command EOL */
    39,  /* (4) line ::= EOL */
    40,  /* (5) command ::= INSTRUCTION */
    40,  /* (6) command ::= INSTRUCTION args */
    40,  /* (7) command ::= INSTRUCTION strings */
    40,  /* (8) command ::= id COLON */
    40,  /* (9) command ::= id ASSIGN expr */
    42,  /* (10) strings ::= strings STRING */
    42,  /* (11) strings ::= STRING */
    41,  /* (12) args ::= argsnc */
    41,  /* (13) args ::= argsnc COMMA */
    45,  /* (14) argsnc ::= argsnc COMMA expr */
    45,  /* (15) argsnc ::= expr */
    43,  /* (16) id ::= IDENTIFIER */
    43,  /* (17) id ::= INSTRUCTION */
    43,  /* (18) id ::= BASE */
    44,  /* (19) expr ::= expr QUESTION expr COLON expr */
    44,  /* (20) expr ::= expr OR expr */
    44,  /* (21) expr ::= expr AND expr */
    44,  /* (22) expr ::= expr BIT_OR expr */
    44,  /* (23) expr ::= expr BIT_XOR expr */
    44,  /* (24) expr ::= expr BIT_AND expr */
    44,  /* (25) expr ::= expr EQ expr */
    44,  /* (26) expr ::= expr NE expr */
    44,  /* (27) expr ::= expr LT expr */
    44,  /* (28) expr ::= expr GT expr */
    44,  /* (29) expr ::= expr LE expr */
    44,  /* (30) expr ::= expr GE expr */
    44,  /* (31) expr ::= expr SHL expr */
    44,  /* (32) expr ::= expr SHR expr */
    44,  /* (33) expr ::= expr PLUS expr */
    44,  /* (34) expr ::= expr MINUS expr */
    44,  /* (35) expr ::= expr MUL expr */
    44,  /* (36) expr ::= expr DIV expr */
    44,  /* (37) expr ::= expr MOD expr */
    44,  /* (38) expr ::= PLUS expr */
    44,  /* (39) expr ::= MINUS expr */
    44,  /* (40) expr ::= NOT expr */
    44,  /* (41) expr ::= BIT_NOT expr */
    44,  /* (42) expr ::= id OPEN args CLOSE */
    44,  /* (43) expr ::= id OPEN CLOSE */
    44,  /* (44) expr ::= OPEN expr CLOSE */
    44,  /* (45) expr ::= DECIMAL */
    44,  /* (46) expr ::= HEX */
    44,  /* (47) expr ::= OCT */
    44,  /* (48) expr ::= id */
    44,  /* (49) expr ::= SOPEN BASE SCLOSE */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) root ::= prog */
   -2,  /* (1) prog ::= prog line */
    0,  /* (2) prog ::= */
   -2,  /* (3) line ::= command EOL */
   -1,  /* (4) line ::= EOL */
   -1,  /* (5) command ::= INSTRUCTION */
   -2,  /* (6) command ::= INSTRUCTION args */
   -2,  /* (7) command ::= INSTRUCTION strings */
   -2,  /* (8) command ::= id COLON */
   -3,  /* (9) command ::= id ASSIGN expr */
   -2,  /* (10) strings ::= strings STRING */
   -1,  /* (11) strings ::= STRING */
   -1,  /* (12) args ::= argsnc */
   -2,  /* (13) args ::= argsnc COMMA */
   -3,  /* (14) argsnc ::= argsnc COMMA expr */
   -1,  /* (15) argsnc ::= expr */
   -1,  /* (16) id ::= IDENTIFIER */
   -1,  /* (17) id ::= INSTRUCTION */
   -1,  /* (18) id ::= BASE */
   -5,  /* (19) expr ::= expr QUESTION expr COLON expr */
   -3,  /* (20) expr ::= expr OR expr */
   -3,  /* (21) expr ::= expr AND expr */
   -3,  /* (22) expr ::= expr BIT_OR expr */
   -3,  /* (23) expr ::= expr BIT_XOR expr */
   -3,  /* (24) expr ::= expr BIT_AND expr */
   -3,  /* (25) expr ::= expr EQ expr */
   -3,  /* (26) expr ::= expr NE expr */
   -3,  /* (27) expr ::= expr LT expr */
   -3,  /* (28) expr ::= expr GT expr */
   -3,  /* (29) expr ::= expr LE expr */
   -3,  /* (30) expr ::= expr GE expr */
   -3,  /* (31) expr ::= expr SHL expr */
   -3,  /* (32) expr ::= expr SHR expr */
   -3,  /* (33) expr ::= expr PLUS expr */
   -3,  /* (34) expr ::= expr MINUS expr */
   -3,  /* (35) expr ::= expr MUL expr */
   -3,  /* (36) expr ::= expr DIV expr */
   -3,  /* (37) expr ::= expr MOD expr */
   -2,  /* (38) expr ::= PLUS expr */
   -2,  /* (39) expr ::= MINUS expr */
   -2,  /* (40) expr ::= NOT expr */
   -2,  /* (41) expr ::= BIT_NOT expr */
   -4,  /* (42) expr ::= id OPEN args CLOSE */
   -3,  /* (43) expr ::= id OPEN CLOSE */
   -3,  /* (44) expr ::= OPEN expr CLOSE */
   -1,  /* (45) expr ::= DECIMAL */
   -1,  /* (46) expr ::= HEX */
   -1,  /* (47) expr ::= OCT */
   -1,  /* (48) expr ::= id */
   -3,  /* (49) expr ::= SOPEN BASE SCLOSE */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  LemonParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  LemonParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  LemonParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* root ::= prog */
#line 17 "src/triasmParser.y"
{ (void)yylhsminor.yy81; lemonResult(th, yymsp[0].minor.yy30); }
#line 1377 "lemon/triasmParser.c"
  yymsp[0].minor.yy81 = yylhsminor.yy81;
        break;
      case 1: /* prog ::= prog line */
#line 22 "src/triasmParser.y"
{ yylhsminor.yy30 = lemonProgAppend(th, yymsp[-1].minor.yy30, yymsp[0].minor.yy1); }
#line 1383 "lemon/triasmParser.c"
  yymsp[-1].minor.yy30 = yylhsminor.yy30;
        break;
      case 2: /* prog ::= */
#line 23 "src/triasmParser.y"
{ yymsp[1].minor.yy30 = NULL; }
#line 1389 "lemon/triasmParser.c"
        break;
      case 3: /* line ::= command EOL */
#line 28 "src/triasmParser.y"
{ yylhsminor.yy1 = yymsp[-1].minor.yy1; }
#line 1394 "lemon/triasmParser.c"
  yy_destructor(yypParser,1,&yymsp[0].minor);
  yymsp[-1].minor.yy1 = yylhsminor.yy1;
        break;
      case 4: /* line ::= EOL */
{  yy_destructor(yypParser,1,&yymsp[0].minor);
#line 29 "src/triasmParser.y"
{ yymsp[0].minor.yy1 = NULL; }
#line 1402 "lemon/triasmParser.c"
}
        break;
      case 5: /* command ::= INSTRUCTION */
#line 34 "src/triasmParser.y"
{ yylhsminor.yy1 = lemonInstrCreate(th, yymsp[0].minor.yy0, NULL, NULL); }
#line 1408 "lemon/triasmParser.c"
  yymsp[0].minor.yy1 = yylhsminor.yy1;
        break;
      case 6: /* command ::= INSTRUCTION args */
#line 35 "src/triasmParser.y"
{ yylhsminor.yy1 = lemonInstrCreate(th, yymsp[-1].minor.yy0, yymsp[0].minor.yy47, NULL); }
#line 1414 "lemon/triasmParser.c"
  yymsp[-1].minor.yy1 = yylhsminor.yy1;
        break;
      case 7: /* command ::= INSTRUCTION strings */
#line 36 "src/triasmParser.y"
{ yylhsminor.yy1 = lemonInstrCreate(th, yymsp[-1].minor.yy0, NULL, yymsp[0].minor.yy76); }
#line 1420 "lemon/triasmParser.c"
  yymsp[-1].minor.yy1 = yylhsminor.yy1;
        break;
      case 8: /* command ::= id COLON */
#line 37 "src/triasmParser.y"
{ yylhsminor.yy1 = lemonLabelCreate(th, yymsp[-1].minor.yy76); }
#line 1426 "lemon/triasmParser.c"
  yy_destructor(yypParser,3,&yymsp[0].minor);
  yymsp[-1].minor.yy1 = yylhsminor.yy1;
        break;
      case 9: /* command ::= id ASSIGN expr */
#line 38 "src/triasmParser.y"
{ yylhsminor.yy1 = lemonAssignCreate(th, yymsp[-2].minor.yy76, yymsp[0].minor.yy45); }
#line 1433 "lemon/triasmParser.c"
  yy_destructor(yypParser,4,&yymsp[-1].minor);
  yymsp[-2].minor.yy1 = yylhsminor.yy1;
        break;
      case 10: /* strings ::= strings STRING */
#line 43 "src/triasmParser.y"
{ yylhsminor.yy76 = lemonStringAppend(th, yymsp[-1].minor.yy76, yymsp[0].minor.yy0); }
#line 1440 "lemon/triasmParser.c"
  yymsp[-1].minor.yy76 = yylhsminor.yy76;
        break;
      case 11: /* strings ::= STRING */
      case 16: /* id ::= IDENTIFIER */ yytestcase(yyruleno==16);
      case 17: /* id ::= INSTRUCTION */ yytestcase(yyruleno==17);
      case 18: /* id ::= BASE */ yytestcase(yyruleno==18);
#line 44 "src/triasmParser.y"
{ yylhsminor.yy76 = yymsp[0].minor.yy0; }
#line 1449 "lemon/triasmParser.c"
  yymsp[0].minor.yy76 = yylhsminor.yy76;
        break;
      case 12: /* args ::= argsnc */
#line 49 "src/triasmParser.y"
{ yylhsminor.yy47 = yymsp[0].minor.yy47; }
#line 1455 "lemon/triasmParser.c"
  yymsp[0].minor.yy47 = yylhsminor.yy47;
        break;
      case 13: /* args ::= argsnc COMMA */
#line 50 "src/triasmParser.y"
{ yylhsminor.yy47 = yymsp[-1].minor.yy47; }
#line 1461 "lemon/triasmParser.c"
  yy_destructor(yypParser,6,&yymsp[0].minor);
  yymsp[-1].minor.yy47 = yylhsminor.yy47;
        break;
      case 14: /* argsnc ::= argsnc COMMA expr */
#line 53 "src/triasmParser.y"
{ yylhsminor.yy47 = lemonArgsAppend(th, yymsp[-2].minor.yy47, yymsp[0].minor.yy45); }
#line 1468 "lemon/triasmParser.c"
  yy_destructor(yypParser,6,&yymsp[-1].minor);
  yymsp[-2].minor.yy47 = yylhsminor.yy47;
        break;
      case 15: /* argsnc ::= expr */
#line 54 "src/triasmParser.y"
{ yylhsminor.yy47 = lemonArgsAppend(th, NULL, yymsp[0].minor.yy45); }
#line 1475 "lemon/triasmParser.c"
  yymsp[0].minor.yy47 = yylhsminor.yy47;
        break;
      case 19: /* expr ::= expr QUESTION expr COLON expr */
#line 69 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprTernary(th, yymsp[-4].minor.yy45, yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1481 "lemon/triasmParser.c"
  yy_destructor(yypParser,9,&yymsp[-3].minor);
  yy_destructor(yypParser,3,&yymsp[-1].minor);
  yymsp[-4].minor.yy45 = yylhsminor.yy45;
        break;
      case 20: /* expr ::= expr OR expr */
#line 73 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'O', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1489 "lemon/triasmParser.c"
  yy_destructor(yypParser,10,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 21: /* expr ::= expr AND expr */
#line 75 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'A', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1496 "lemon/triasmParser.c"
  yy_destructor(yypParser,11,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 22: /* expr ::= expr BIT_OR expr */
#line 77 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '|', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1503 "lemon/triasmParser.c"
  yy_destructor(yypParser,12,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 23: /* expr ::= expr BIT_XOR expr */
#line 79 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '^', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1510 "lemon/triasmParser.c"
  yy_destructor(yypParser,13,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 24: /* expr ::= expr BIT_AND expr */
#line 81 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '&', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1517 "lemon/triasmParser.c"
  yy_destructor(yypParser,14,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 25: /* expr ::= expr EQ expr */
#line 85 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'E', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1524 "lemon/triasmParser.c"
  yy_destructor(yypParser,15,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 26: /* expr ::= expr NE expr */
#line 86 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'N', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1531 "lemon/triasmParser.c"
  yy_destructor(yypParser,16,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 27: /* expr ::= expr LT expr */
#line 88 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '<', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1538 "lemon/triasmParser.c"
  yy_destructor(yypParser,17,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 28: /* expr ::= expr GT expr */
#line 89 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '>', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1545 "lemon/triasmParser.c"
  yy_destructor(yypParser,18,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 29: /* expr ::= expr LE expr */
#line 90 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'L', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1552 "lemon/triasmParser.c"
  yy_destructor(yypParser,19,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 30: /* expr ::= expr GE expr */
#line 91 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'G', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1559 "lemon/triasmParser.c"
  yy_destructor(yypParser,20,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 31: /* expr ::= expr SHL expr */
#line 95 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'r', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1566 "lemon/triasmParser.c"
  yy_destructor(yypParser,21,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 32: /* expr ::= expr SHR expr */
#line 96 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, 'l', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1573 "lemon/triasmParser.c"
  yy_destructor(yypParser,22,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 33: /* expr ::= expr PLUS expr */
#line 100 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '+', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1580 "lemon/triasmParser.c"
  yy_destructor(yypParser,23,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 34: /* expr ::= expr MINUS expr */
#line 101 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '-', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1587 "lemon/triasmParser.c"
  yy_destructor(yypParser,24,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 35: /* expr ::= expr MUL expr */
#line 103 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '*', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1594 "lemon/triasmParser.c"
  yy_destructor(yypParser,25,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 36: /* expr ::= expr DIV expr */
#line 104 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '/', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1601 "lemon/triasmParser.c"
  yy_destructor(yypParser,26,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 37: /* expr ::= expr MOD expr */
#line 105 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprBinOp(th, '%', yymsp[-2].minor.yy45, yymsp[0].minor.yy45); }
#line 1608 "lemon/triasmParser.c"
  yy_destructor(yypParser,27,&yymsp[-1].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 38: /* expr ::= PLUS expr */
{  yy_destructor(yypParser,23,&yymsp[-1].minor);
#line 109 "src/triasmParser.y"
{ yymsp[-1].minor.yy45 = yymsp[0].minor.yy45; }
#line 1616 "lemon/triasmParser.c"
}
        break;
      case 39: /* expr ::= MINUS expr */
{  yy_destructor(yypParser,24,&yymsp[-1].minor);
#line 110 "src/triasmParser.y"
{ yymsp[-1].minor.yy45 = lemonExprUnOp(th, 'M', yymsp[0].minor.yy45); }
#line 1623 "lemon/triasmParser.c"
}
        break;
      case 40: /* expr ::= NOT expr */
{  yy_destructor(yypParser,28,&yymsp[-1].minor);
#line 111 "src/triasmParser.y"
{ yymsp[-1].minor.yy45 = lemonExprUnOp(th, '!', yymsp[0].minor.yy45); }
#line 1630 "lemon/triasmParser.c"
}
        break;
      case 41: /* expr ::= BIT_NOT expr */
{  yy_destructor(yypParser,29,&yymsp[-1].minor);
#line 112 "src/triasmParser.y"
{ yymsp[-1].minor.yy45 = lemonExprUnOp(th, '~', yymsp[0].minor.yy45); }
#line 1637 "lemon/triasmParser.c"
}
        break;
      case 42: /* expr ::= id OPEN args CLOSE */
#line 115 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprCall(th, yymsp[-3].minor.yy76, yymsp[-1].minor.yy47); }
#line 1643 "lemon/triasmParser.c"
  yy_destructor(yypParser,30,&yymsp[-2].minor);
  yy_destructor(yypParser,31,&yymsp[0].minor);
  yymsp[-3].minor.yy45 = yylhsminor.yy45;
        break;
      case 43: /* expr ::= id OPEN CLOSE */
#line 116 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprCall(th, yymsp[-2].minor.yy76, NULL); }
#line 1651 "lemon/triasmParser.c"
  yy_destructor(yypParser,30,&yymsp[-1].minor);
  yy_destructor(yypParser,31,&yymsp[0].minor);
  yymsp[-2].minor.yy45 = yylhsminor.yy45;
        break;
      case 44: /* expr ::= OPEN expr CLOSE */
{  yy_destructor(yypParser,30,&yymsp[-2].minor);
#line 119 "src/triasmParser.y"
{ yymsp[-2].minor.yy45 = yymsp[-1].minor.yy45; }
#line 1660 "lemon/triasmParser.c"
  yy_destructor(yypParser,31,&yymsp[0].minor);
}
        break;
      case 45: /* expr ::= DECIMAL */
#line 122 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprNumber(th, yymsp[0].minor.yy0, 10); }
#line 1667 "lemon/triasmParser.c"
  yymsp[0].minor.yy45 = yylhsminor.yy45;
        break;
      case 46: /* expr ::= HEX */
#line 123 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprNumber(th, yymsp[0].minor.yy0, 16); }
#line 1673 "lemon/triasmParser.c"
  yymsp[0].minor.yy45 = yylhsminor.yy45;
        break;
      case 47: /* expr ::= OCT */
#line 124 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprNumber(th, yymsp[0].minor.yy0, 8); }
#line 1679 "lemon/triasmParser.c"
  yymsp[0].minor.yy45 = yylhsminor.yy45;
        break;
      case 48: /* expr ::= id */
#line 125 "src/triasmParser.y"
{ yylhsminor.yy45 = lemonExprIdentifier(th, yymsp[0].minor.yy76); }
#line 1685 "lemon/triasmParser.c"
  yymsp[0].minor.yy45 = yylhsminor.yy45;
        break;
      case 49: /* expr ::= SOPEN BASE SCLOSE */
{  yy_destructor(yypParser,35,&yymsp[-2].minor);
#line 126 "src/triasmParser.y"
{ yymsp[-2].minor.yy45 = lemonExprBase(th, yymsp[-1].minor.yy0); }
#line 1692 "lemon/triasmParser.c"
  yy_destructor(yypParser,36,&yymsp[0].minor);
}
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 10 "src/triasmParser.y"
 lemonFailure(th); 
#line 1740 "lemon/triasmParser.c"
/************ End %parse_failure code *****************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  LemonParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 8 "src/triasmParser.y"
 lemonError(th); 
#line 1761 "lemon/triasmParser.c"
/************ End %syntax_error code ******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  LemonParseARG_FETCH
  LemonParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  LemonParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  LemonParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "LemonParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void LemonParse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  LemonParseTOKENTYPE yyminor       /* The value for the token */
  LemonParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  LemonParseCTX_FETCH
  LemonParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor LemonParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int LemonParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
