
#include "common.hh"

#include "WasmConsts.hh"
#include "WasmData.hh"

#include "InstructionDesc.hh"

Array$<InstrDesc$> instrDescTable = {
    /* 0x00 */ InstrDesc{ .name = "unreachable" },
    /* 0x01 */ InstrDesc{ .name = "nop" },
    /* 0x02 */ InstrDesc{ .name = "block",         .imm = "*" },
    /* 0x03 */ InstrDesc{ .name = "loop",          .imm = "*" },
    /* 0x04 */ InstrDesc{ .name = "if",            .imm = "*" },
    /* 0x05 */ InstrDesc{ .name = "else",          .imm = "*" },
    /* 0x06 */ InstrDesc{ },
    /* 0x07 */ InstrDesc{ },
    /* 0x08 */ InstrDesc{ },
    /* 0x09 */ InstrDesc{ },
    /* 0x0A */ InstrDesc{ },
    /* 0x0B */ InstrDesc{ .name = "end",           .imm = "*" },
    /* 0x0C */ InstrDesc{ .name = "br",            .imm = "u" },
    /* 0x0D */ InstrDesc{ .name = "br_if",         .imm = "u" },
    /* 0x0E */ InstrDesc{ .name = "br_table",      .imm = "*" },
    /* 0x0F */ InstrDesc{ .name = "return" },
    /* 0x10 */ InstrDesc{ .name = "call",          .imm = "u" },
    /* 0x11 */ InstrDesc{ .name = "call_indirect", .imm = "uu" },
    /* 0x12 */ InstrDesc{ },
    /* 0x13 */ InstrDesc{ },
    /* 0x14 */ InstrDesc{ },
    /* 0x15 */ InstrDesc{ },
    /* 0x16 */ InstrDesc{ },
    /* 0x17 */ InstrDesc{ },
    /* 0x18 */ InstrDesc{ },
    /* 0x19 */ InstrDesc{ },
    /* 0x1A */ InstrDesc{ .name = "drop" },
    /* 0x1B */ InstrDesc{ .name = "select" },
    /* 0x1C */ InstrDesc{ .name = "select",        .imm = "*" },
    /* 0x1D */ InstrDesc{ },
    /* 0x1E */ InstrDesc{ },
    /* 0x1F */ InstrDesc{ },
    /* 0x20 */ InstrDesc{ .name = "local.get",     .imm = "u" },
    /* 0x21 */ InstrDesc{ .name = "local.set",     .imm = "u" },
    /* 0x22 */ InstrDesc{ .name = "local.tee",     .imm = "u" },
    /* 0x23 */ InstrDesc{ .name = "global.get",    .imm = "u" },
    /* 0x24 */ InstrDesc{ .name = "global.set",    .imm = "u" },
    /* 0x25 */ InstrDesc{ .name = "table.get",     .imm = "u" },
    /* 0x26 */ InstrDesc{ .name = "table.set",     .imm = "u" },
    /* 0x27 */ InstrDesc{ },
    /* 0x28 */ InstrDesc{ .name = "i32.load",      .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x29 */ InstrDesc{ .name = "i64.load",      .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x2A */ InstrDesc{ .name = "f32.load",      .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_F32 } },
    /* 0x2B */ InstrDesc{ .name = "f64.load",      .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_F64 } },
    /* 0x2C */ InstrDesc{ .name = "i32.load8_s",   .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x2D */ InstrDesc{ .name = "i32.load8_u",   .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x2E */ InstrDesc{ .name = "i32.load16_s",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x2F */ InstrDesc{ .name = "i32.load16_u",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x30 */ InstrDesc{ .name = "i64.load8_s",   .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x31 */ InstrDesc{ .name = "i64.load8_u",   .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x32 */ InstrDesc{ .name = "i64.load16_s",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x33 */ InstrDesc{ .name = "i64.load16_u",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x34 */ InstrDesc{ .name = "i64.load32_s",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x35 */ InstrDesc{ .name = "i64.load32_u",  .imm = "uu", .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0x36 */ InstrDesc{ .name = "i32.store",     .imm = "uu", .input = { TYPE_I32, TYPE_I32 } },
    /* 0x37 */ InstrDesc{ .name = "i64.store",     .imm = "uu", .input = { TYPE_I32, TYPE_I64 } },
    /* 0x38 */ InstrDesc{ .name = "f32.store",     .imm = "uu", .input = { TYPE_I32, TYPE_F32 } },
    /* 0x39 */ InstrDesc{ .name = "f64.store",     .imm = "uu", .input = { TYPE_I32, TYPE_F64 } },
    /* 0x3A */ InstrDesc{ .name = "i32.store8",    .imm = "uu", .input = { TYPE_I32, TYPE_I32 } },
    /* 0x3B */ InstrDesc{ .name = "i32.store16",   .imm = "uu", .input = { TYPE_I32, TYPE_I32 } },
    /* 0x3C */ InstrDesc{ .name = "i64.store8",    .imm = "uu", .input = { TYPE_I32, TYPE_I64 } },
    /* 0x3D */ InstrDesc{ .name = "i64.store16",   .imm = "uu", .input = { TYPE_I32, TYPE_I64 } },
    /* 0x3E */ InstrDesc{ .name = "i64.store32",   .imm = "uu", .input = { TYPE_I32, TYPE_I64 } },
    /* 0x3F */ InstrDesc{ .name = "memory.size",   .imm = "b",                                   .output = { TYPE_I32 } },
    /* 0x40 */ InstrDesc{ .name = "memory.grow",   .imm = "b",  .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x41 */ InstrDesc{ .name = "i32.const",     .imm = "i",                                   .output = { TYPE_I32 } },
    /* 0x42 */ InstrDesc{ .name = "i64.const",     .imm = "l",                                   .output = { TYPE_I64 } },
    /* 0x43 */ InstrDesc{ .name = "f32.const",     .imm = "f",                                   .output = { TYPE_F32 } },
    /* 0x44 */ InstrDesc{ .name = "f64.const",     .imm = "d",                                   .output = { TYPE_F64 } },
    /* 0x45 */ InstrDesc{ .name = "i32.eqz",                    .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x46 */ InstrDesc{ .name = "i32.eq",                     .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x47 */ InstrDesc{ .name = "i32.ne",                     .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x48 */ InstrDesc{ .name = "i32.lt_s",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x49 */ InstrDesc{ .name = "i32.lt_u",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4A */ InstrDesc{ .name = "i32.gt_s",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4B */ InstrDesc{ .name = "i32.gt_u",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4C */ InstrDesc{ .name = "i32.le_s",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4D */ InstrDesc{ .name = "i32.le_u",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4E */ InstrDesc{ .name = "i32.ge_s",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x4F */ InstrDesc{ .name = "i32.ge_u",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x50 */ InstrDesc{ .name = "i64.eqz",                    .input = { TYPE_I64 },           .output = { TYPE_I32 } },
    /* 0x51 */ InstrDesc{ .name = "i64.eq",                     .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x52 */ InstrDesc{ .name = "i64.ne",                     .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x53 */ InstrDesc{ .name = "i64.lt_s",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x54 */ InstrDesc{ .name = "i64.lt_u",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x55 */ InstrDesc{ .name = "i64.gt_s",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x56 */ InstrDesc{ .name = "i64.gt_u",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x57 */ InstrDesc{ .name = "i64.le_s",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x58 */ InstrDesc{ .name = "i64.le_u",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x59 */ InstrDesc{ .name = "i64.ge_s",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x5A */ InstrDesc{ .name = "i64.ge_u",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I32 } },
    /* 0x5B */ InstrDesc{ .name = "f32.eq",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x5C */ InstrDesc{ .name = "f32.ne",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x5D */ InstrDesc{ .name = "f32.lt",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x5E */ InstrDesc{ .name = "f32.gt",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x5F */ InstrDesc{ .name = "f32.le",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x60 */ InstrDesc{ .name = "f32.ge",                     .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_I32 } },
    /* 0x61 */ InstrDesc{ .name = "f64.eq",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x62 */ InstrDesc{ .name = "f64.ne",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x63 */ InstrDesc{ .name = "f64.lt",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x64 */ InstrDesc{ .name = "f64.gt",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x65 */ InstrDesc{ .name = "f64.le",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x66 */ InstrDesc{ .name = "f64.ge",                     .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_I32 } },
    /* 0x67 */ InstrDesc{ .name = "i32.clz",                    .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x68 */ InstrDesc{ .name = "i32.ctz",                    .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x69 */ InstrDesc{ .name = "i32.popcnt",                 .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0x6A */ InstrDesc{ .name = "i32.add",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x6B */ InstrDesc{ .name = "i32.sub",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x6C */ InstrDesc{ .name = "i32.mul",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x6D */ InstrDesc{ .name = "i32.div_s",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x6E */ InstrDesc{ .name = "i32.div_u",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x6F */ InstrDesc{ .name = "i32.rem_s",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x70 */ InstrDesc{ .name = "i32.rem_u",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x71 */ InstrDesc{ .name = "i32.and",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x72 */ InstrDesc{ .name = "i32.or",                     .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x73 */ InstrDesc{ .name = "i32.xor",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x74 */ InstrDesc{ .name = "i32.shl",                    .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x75 */ InstrDesc{ .name = "i32.shr_s",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x76 */ InstrDesc{ .name = "i32.shr_u",                  .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x77 */ InstrDesc{ .name = "i32.rotl",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x78 */ InstrDesc{ .name = "i32.rotr",                   .input = { TYPE_I32, TYPE_I32 }, .output = { TYPE_I32 } },
    /* 0x79 */ InstrDesc{ .name = "i64.clz",                    .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0x7A */ InstrDesc{ .name = "i64.ctz",                    .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0x7B */ InstrDesc{ .name = "i64.popcnt",                 .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0x7C */ InstrDesc{ .name = "i64.add",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x7D */ InstrDesc{ .name = "i64.sub",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x7E */ InstrDesc{ .name = "i64.mul",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x7F */ InstrDesc{ .name = "i64.div_s",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x80 */ InstrDesc{ .name = "i64.div_u",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x81 */ InstrDesc{ .name = "i64.rem_s",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x82 */ InstrDesc{ .name = "i64.rem_u",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x83 */ InstrDesc{ .name = "i64.and",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x84 */ InstrDesc{ .name = "i64.or",                     .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x85 */ InstrDesc{ .name = "i64.xor",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x86 */ InstrDesc{ .name = "i64.shl",                    .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x87 */ InstrDesc{ .name = "i64.shr_s",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x88 */ InstrDesc{ .name = "i64.shr_u",                  .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x89 */ InstrDesc{ .name = "i64.rotl",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x8A */ InstrDesc{ .name = "i64.rotr",                   .input = { TYPE_I64, TYPE_I64 }, .output = { TYPE_I64 } },
    /* 0x8B */ InstrDesc{ .name = "f32.abs",                    .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x8C */ InstrDesc{ .name = "f32.neg",                    .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x8D */ InstrDesc{ .name = "f32.ceil",                   .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x8E */ InstrDesc{ .name = "f32.floor",                  .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x8F */ InstrDesc{ .name = "f32.trunc",                  .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x90 */ InstrDesc{ .name = "f32.nearest",                .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x91 */ InstrDesc{ .name = "f32.sqrt",                   .input = { TYPE_F32 },           .output = { TYPE_F32 } },
    /* 0x92 */ InstrDesc{ .name = "f32.add",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x93 */ InstrDesc{ .name = "f32.sub",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x94 */ InstrDesc{ .name = "f32.mul",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x95 */ InstrDesc{ .name = "f32.div",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x96 */ InstrDesc{ .name = "f32.min",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x97 */ InstrDesc{ .name = "f32.max",                    .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x98 */ InstrDesc{ .name = "f32.copysign",               .input = { TYPE_F32, TYPE_F32 }, .output = { TYPE_F32 } },
    /* 0x99 */ InstrDesc{ .name = "f64.abs",                    .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9A */ InstrDesc{ .name = "f64.neg",                    .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9B */ InstrDesc{ .name = "f64.ceil",                   .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9C */ InstrDesc{ .name = "f64.floor",                  .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9D */ InstrDesc{ .name = "f64.trunc",                  .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9E */ InstrDesc{ .name = "f64.nearest",                .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0x9F */ InstrDesc{ .name = "f64.sqrt",                   .input = { TYPE_F64 },           .output = { TYPE_F64 } },
    /* 0xA0 */ InstrDesc{ .name = "f64.add",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA1 */ InstrDesc{ .name = "f64.sub",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA2 */ InstrDesc{ .name = "f64.mul",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA3 */ InstrDesc{ .name = "f64.div",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA4 */ InstrDesc{ .name = "f64.min",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA5 */ InstrDesc{ .name = "f64.max",                    .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA6 */ InstrDesc{ .name = "f64.copysign",               .input = { TYPE_F64, TYPE_F64 }, .output = { TYPE_F64 } },
    /* 0xA7 */ InstrDesc{ .name = "i32.wrap_i64",               .input = { TYPE_I64 },           .output = { TYPE_I32 } },
    /* 0xA8 */ InstrDesc{ .name = "i32.trunc_f32_s",            .input = { TYPE_F32 },           .output = { TYPE_I32 } },
    /* 0xA9 */ InstrDesc{ .name = "i32.trunc_f32_u",            .input = { TYPE_F32 },           .output = { TYPE_I32 } },
    /* 0xAA */ InstrDesc{ .name = "i32.trunc_f64_s",            .input = { TYPE_F64 },           .output = { TYPE_I32 } },
    /* 0xAB */ InstrDesc{ .name = "i32.trunc_f64_u",            .input = { TYPE_F64 },           .output = { TYPE_I32 } },
    /* 0xAC */ InstrDesc{ .name = "i64.extend_i32_s",           .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0xAD */ InstrDesc{ .name = "i64.extend_i32_u",           .input = { TYPE_I32 },           .output = { TYPE_I64 } },
    /* 0xAE */ InstrDesc{ .name = "i64.trunc_f32_s",            .input = { TYPE_F32 },           .output = { TYPE_I64 } },
    /* 0xAF */ InstrDesc{ .name = "i64.trunc_f32_u",            .input = { TYPE_F32 },           .output = { TYPE_I64 } },
    /* 0xB0 */ InstrDesc{ .name = "i64.trunc_f64_s",            .input = { TYPE_F64 },           .output = { TYPE_I64 } },
    /* 0xB1 */ InstrDesc{ .name = "i64.trunc_f64_u",            .input = { TYPE_F64 },           .output = { TYPE_I64 } },
    /* 0xB2 */ InstrDesc{ .name = "f32.convert_i32_s",          .input = { TYPE_I32 },           .output = { TYPE_F32 } },
    /* 0xB3 */ InstrDesc{ .name = "f32.convert_i32_u",          .input = { TYPE_I32 },           .output = { TYPE_F32 } },
    /* 0xB4 */ InstrDesc{ .name = "f32.convert_i64_s",          .input = { TYPE_I64 },           .output = { TYPE_F32 } },
    /* 0xB5 */ InstrDesc{ .name = "f32.convert_i64_u",          .input = { TYPE_I64 },           .output = { TYPE_F32 } },
    /* 0xB6 */ InstrDesc{ .name = "f32.demote_f64",             .input = { TYPE_F64 },           .output = { TYPE_F32 } },
    /* 0xB7 */ InstrDesc{ .name = "f64.convert_i32_s",          .input = { TYPE_I32 },           .output = { TYPE_F64 } },
    /* 0xB8 */ InstrDesc{ .name = "f64.convert_i32_u",          .input = { TYPE_I32 },           .output = { TYPE_F64 } },
    /* 0xB9 */ InstrDesc{ .name = "f64.convert_i64_s",          .input = { TYPE_I64 },           .output = { TYPE_F64 } },
    /* 0xBA */ InstrDesc{ .name = "f64.convert_i64_u",          .input = { TYPE_I64 },           .output = { TYPE_F64 } },
    /* 0xBB */ InstrDesc{ .name = "f64.promote_f32",            .input = { TYPE_F32 },           .output = { TYPE_F64 } },
    /* 0xBC */ InstrDesc{ .name = "i32.reinterpret_f32",        .input = { TYPE_F32 },           .output = { TYPE_I32 } },
    /* 0xBD */ InstrDesc{ .name = "i64.reinterpret_f64",        .input = { TYPE_F64 },           .output = { TYPE_I64 } },
    /* 0xBE */ InstrDesc{ .name = "f32.reinterpret_i32",        .input = { TYPE_I32 },           .output = { TYPE_F32 } },
    /* 0xBF */ InstrDesc{ .name = "f64.reinterpret_i64",        .input = { TYPE_I64 },           .output = { TYPE_F64 } },
    /* 0xC0 */ InstrDesc{ .name = "i32.extend8_s",              .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0xC1 */ InstrDesc{ .name = "i32.extend16_s",             .input = { TYPE_I32 },           .output = { TYPE_I32 } },
    /* 0xC2 */ InstrDesc{ .name = "i64.extend8_s",              .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0xC3 */ InstrDesc{ .name = "i64.extend16_s",             .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0xC4 */ InstrDesc{ .name = "i64.extend32_s",             .input = { TYPE_I64 },           .output = { TYPE_I64 } },
    /* 0xC5 */ InstrDesc{ },
    /* 0xC6 */ InstrDesc{ },
    /* 0xC7 */ InstrDesc{ },
    /* 0xC8 */ InstrDesc{ },
    /* 0xC9 */ InstrDesc{ },
    /* 0xCA */ InstrDesc{ },
    /* 0xCB */ InstrDesc{ },
    /* 0xCC */ InstrDesc{ },
    /* 0xCD */ InstrDesc{ },
    /* 0xCE */ InstrDesc{ },
    /* 0xCF */ InstrDesc{ },
    /* 0xD0 */ InstrDesc{ .name = "ref.null",      .imm = "b" },
    /* 0xD1 */ InstrDesc{ .name = "ref.is_null" },
    /* 0xD2 */ InstrDesc{ .name = "ref.func",      .imm = "u" },
    /* 0xD3 */ InstrDesc{ },
    /* 0xD4 */ InstrDesc{ },
    /* 0xD5 */ InstrDesc{ },
    /* 0xD6 */ InstrDesc{ },
    /* 0xD7 */ InstrDesc{ },
    /* 0xD8 */ InstrDesc{ },
    /* 0xD9 */ InstrDesc{ },
    /* 0xDA */ InstrDesc{ },
    /* 0xDB */ InstrDesc{ },
    /* 0xDC */ InstrDesc{ },
    /* 0xDD */ InstrDesc{ },
    /* 0xDE */ InstrDesc{ },
    /* 0xDF */ InstrDesc{ },
    /* 0xE0 */ InstrDesc{ },
    /* 0xE1 */ InstrDesc{ },
    /* 0xE2 */ InstrDesc{ },
    /* 0xE3 */ InstrDesc{ },
    /* 0xE4 */ InstrDesc{ },
    /* 0xE5 */ InstrDesc{ },
    /* 0xE6 */ InstrDesc{ },
    /* 0xE7 */ InstrDesc{ },
    /* 0xE8 */ InstrDesc{ },
    /* 0xE9 */ InstrDesc{ },
    /* 0xEA */ InstrDesc{ },
    /* 0xEB */ InstrDesc{ },
    /* 0xEC */ InstrDesc{ },
    /* 0xED */ InstrDesc{ },
    /* 0xEE */ InstrDesc{ },
    /* 0xEF */ InstrDesc{ },
    /* 0xF0 */ InstrDesc{ },
    /* 0xF1 */ InstrDesc{ },
    /* 0xF2 */ InstrDesc{ },
    /* 0xF3 */ InstrDesc{ },
    /* 0xF4 */ InstrDesc{ },
    /* 0xF5 */ InstrDesc{ },
    /* 0xF6 */ InstrDesc{ },
    /* 0xF7 */ InstrDesc{ },
    /* 0xF8 */ InstrDesc{ },
    /* 0xF9 */ InstrDesc{ },
    /* 0xFA */ InstrDesc{ },
    /* 0xFB */ InstrDesc{ },
    /* 0xFC */ InstrDesc{ .name = "",              .imm = "*" }, // Extended instructions
    /* 0xFD */ InstrDesc{ },
    /* 0xFE */ InstrDesc{ },
    /* 0xFF */ InstrDesc{ },
};

Array$<InstrDesc$> extInstrDescTable = {
    /* 0xFC 0x00 */ InstrDesc{ .name = "i32.trunc_sat_f32_s",             .input = { TYPE_F32 },                     .output = { TYPE_I32 } },
    /* 0xFC 0x01 */ InstrDesc{ .name = "i32.trunc_sat_f32_u",             .input = { TYPE_F32 },                     .output = { TYPE_I32 } },
    /* 0xFC 0x02 */ InstrDesc{ .name = "i32.trunc_sat_f64_s",             .input = { TYPE_F64 },                     .output = { TYPE_I32 } },
    /* 0xFC 0x03 */ InstrDesc{ .name = "i32.trunc_sat_f64_u",             .input = { TYPE_F64 },                     .output = { TYPE_I32 } },
    /* 0xFC 0x04 */ InstrDesc{ .name = "i64.trunc_sat_f32_s",             .input = { TYPE_F32 },                     .output = { TYPE_I64 } },
    /* 0xFC 0x05 */ InstrDesc{ .name = "i64.trunc_sat_f32_u",             .input = { TYPE_F32 },                     .output = { TYPE_I64 } },
    /* 0xFC 0x06 */ InstrDesc{ .name = "i64.trunc_sat_f64_s",             .input = { TYPE_F64 },                     .output = { TYPE_I64 } },
    /* 0xFC 0x07 */ InstrDesc{ .name = "i64.trunc_sat_f64_u",             .input = { TYPE_F64 },                     .output = { TYPE_I64 } },
    /* 0xFC 0x08 */ InstrDesc{ .name = "memory.init",        .imm = "u",  .input = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x09 */ InstrDesc{ .name = "data.drop",          .imm = "u" },
    /* 0xFC 0x0A */ InstrDesc{ .name = "memory.copy",        .imm = "bb", .input = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0B */ InstrDesc{ .name = "memory.fill",        .imm = "b",  .input = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0C */ InstrDesc{ .name = "table.init",         .imm = "uu", .input = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0D */ InstrDesc{ .name = "elem.drop",          .imm = "u" },
    /* 0xFC 0x0E */ InstrDesc{ .name = "table.copy",         .imm = "uu", .input = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0F */ InstrDesc{ .name = "table.grow",         .imm = "u" },
    /* 0xFC 0x10 */ InstrDesc{ .name = "table.size",         .imm = "u",                                             .output = { TYPE_I32 } },
    /* 0xFC 0x11 */ InstrDesc{ .name = "table.fill",         .imm = "u" },
};
