
#include "common.hh"

#include "WasmConsts.hh"
#include "WasmData.hh"

#include "WasmInstrDesc.hh"

Array$<WasmInstrDesc$> instrDescTable = {
    /* 0x00 */ WasmInstrDesc{ .name = "unreachable" },
    /* 0x01 */ WasmInstrDesc{ .name = "nop" },
    /* 0x02 */ WasmInstrDesc{ .name = "block",         .imm = "*" },
    /* 0x03 */ WasmInstrDesc{ .name = "loop",          .imm = "*" },
    /* 0x04 */ WasmInstrDesc{ .name = "if",            .imm = "*" },
    /* 0x05 */ WasmInstrDesc{ .name = "else",          .imm = "*" },
    /* 0x06 */ WasmInstrDesc{ },
    /* 0x07 */ WasmInstrDesc{ },
    /* 0x08 */ WasmInstrDesc{ },
    /* 0x09 */ WasmInstrDesc{ },
    /* 0x0A */ WasmInstrDesc{ },
    /* 0x0B */ WasmInstrDesc{ .name = "end",           .imm = "*" },
    /* 0x0C */ WasmInstrDesc{ .name = "br",            .imm = "u" },
    /* 0x0D */ WasmInstrDesc{ .name = "br_if",         .imm = "u" },
    /* 0x0E */ WasmInstrDesc{ .name = "br_table",      .imm = "*" },
    /* 0x0F */ WasmInstrDesc{ .name = "return" },
    /* 0x10 */ WasmInstrDesc{ .name = "call",          .imm = "u" },
    /* 0x11 */ WasmInstrDesc{ .name = "call_indirect", .imm = "uu" },
    /* 0x12 */ WasmInstrDesc{ },
    /* 0x13 */ WasmInstrDesc{ },
    /* 0x14 */ WasmInstrDesc{ },
    /* 0x15 */ WasmInstrDesc{ },
    /* 0x16 */ WasmInstrDesc{ },
    /* 0x17 */ WasmInstrDesc{ },
    /* 0x18 */ WasmInstrDesc{ },
    /* 0x19 */ WasmInstrDesc{ },
    /* 0x1A */ WasmInstrDesc{ .name = "drop" },
    /* 0x1B */ WasmInstrDesc{ .name = "select" },
    /* 0x1C */ WasmInstrDesc{ .name = "select",        .imm = "*" },
    /* 0x1D */ WasmInstrDesc{ },
    /* 0x1E */ WasmInstrDesc{ },
    /* 0x1F */ WasmInstrDesc{ },
    /* 0x20 */ WasmInstrDesc{ .name = "local.get",     .imm = "u" },
    /* 0x21 */ WasmInstrDesc{ .name = "local.set",     .imm = "u" },
    /* 0x22 */ WasmInstrDesc{ .name = "local.tee",     .imm = "u" },
    /* 0x23 */ WasmInstrDesc{ .name = "global.get",    .imm = "u" },
    /* 0x24 */ WasmInstrDesc{ .name = "global.set",    .imm = "u" },
    /* 0x25 */ WasmInstrDesc{ .name = "table.get",     .imm = "u" },
    /* 0x26 */ WasmInstrDesc{ .name = "table.set",     .imm = "u" },
    /* 0x27 */ WasmInstrDesc{ },
    /* 0x28 */ WasmInstrDesc{ .name = "i32.load",      .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x29 */ WasmInstrDesc{ .name = "i64.load",      .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x2A */ WasmInstrDesc{ .name = "f32.load",      .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_F32 } },
    /* 0x2B */ WasmInstrDesc{ .name = "f64.load",      .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_F64 } },
    /* 0x2C */ WasmInstrDesc{ .name = "i32.load8_s",   .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x2D */ WasmInstrDesc{ .name = "i32.load8_u",   .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x2E */ WasmInstrDesc{ .name = "i32.load16_s",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x2F */ WasmInstrDesc{ .name = "i32.load16_u",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x30 */ WasmInstrDesc{ .name = "i64.load8_s",   .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x31 */ WasmInstrDesc{ .name = "i64.load8_u",   .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x32 */ WasmInstrDesc{ .name = "i64.load16_s",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x33 */ WasmInstrDesc{ .name = "i64.load16_u",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x34 */ WasmInstrDesc{ .name = "i64.load32_s",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x35 */ WasmInstrDesc{ .name = "i64.load32_u",  .imm = "uu", .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0x36 */ WasmInstrDesc{ .name = "i32.store",     .imm = "uu", .param = { TYPE_I32, TYPE_I32 } },
    /* 0x37 */ WasmInstrDesc{ .name = "i64.store",     .imm = "uu", .param = { TYPE_I32, TYPE_I64 } },
    /* 0x38 */ WasmInstrDesc{ .name = "f32.store",     .imm = "uu", .param = { TYPE_I32, TYPE_F32 } },
    /* 0x39 */ WasmInstrDesc{ .name = "f64.store",     .imm = "uu", .param = { TYPE_I32, TYPE_F64 } },
    /* 0x3A */ WasmInstrDesc{ .name = "i32.store8",    .imm = "uu", .param = { TYPE_I32, TYPE_I32 } },
    /* 0x3B */ WasmInstrDesc{ .name = "i32.store16",   .imm = "uu", .param = { TYPE_I32, TYPE_I32 } },
    /* 0x3C */ WasmInstrDesc{ .name = "i64.store8",    .imm = "uu", .param = { TYPE_I32, TYPE_I64 } },
    /* 0x3D */ WasmInstrDesc{ .name = "i64.store16",   .imm = "uu", .param = { TYPE_I32, TYPE_I64 } },
    /* 0x3E */ WasmInstrDesc{ .name = "i64.store32",   .imm = "uu", .param = { TYPE_I32, TYPE_I64 } },
    /* 0x3F */ WasmInstrDesc{ .name = "memory.size",   .imm = "b",                                   .result = { TYPE_I32 } },
    /* 0x40 */ WasmInstrDesc{ .name = "memory.grow",   .imm = "b",  .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x41 */ WasmInstrDesc{ .name = "i32.const",     .imm = "i",                                   .result = { TYPE_I32 } },
    /* 0x42 */ WasmInstrDesc{ .name = "i64.const",     .imm = "l",                                   .result = { TYPE_I64 } },
    /* 0x43 */ WasmInstrDesc{ .name = "f32.const",     .imm = "f",                                   .result = { TYPE_F32 } },
    /* 0x44 */ WasmInstrDesc{ .name = "f64.const",     .imm = "d",                                   .result = { TYPE_F64 } },
    /* 0x45 */ WasmInstrDesc{ .name = "i32.eqz",                    .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x46 */ WasmInstrDesc{ .name = "i32.eq",                     .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x47 */ WasmInstrDesc{ .name = "i32.ne",                     .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x48 */ WasmInstrDesc{ .name = "i32.lt_s",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x49 */ WasmInstrDesc{ .name = "i32.lt_u",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4A */ WasmInstrDesc{ .name = "i32.gt_s",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4B */ WasmInstrDesc{ .name = "i32.gt_u",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4C */ WasmInstrDesc{ .name = "i32.le_s",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4D */ WasmInstrDesc{ .name = "i32.le_u",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4E */ WasmInstrDesc{ .name = "i32.ge_s",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x4F */ WasmInstrDesc{ .name = "i32.ge_u",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x50 */ WasmInstrDesc{ .name = "i64.eqz",                    .param = { TYPE_I64 },           .result = { TYPE_I32 } },
    /* 0x51 */ WasmInstrDesc{ .name = "i64.eq",                     .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x52 */ WasmInstrDesc{ .name = "i64.ne",                     .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x53 */ WasmInstrDesc{ .name = "i64.lt_s",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x54 */ WasmInstrDesc{ .name = "i64.lt_u",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x55 */ WasmInstrDesc{ .name = "i64.gt_s",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x56 */ WasmInstrDesc{ .name = "i64.gt_u",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x57 */ WasmInstrDesc{ .name = "i64.le_s",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x58 */ WasmInstrDesc{ .name = "i64.le_u",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x59 */ WasmInstrDesc{ .name = "i64.ge_s",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x5A */ WasmInstrDesc{ .name = "i64.ge_u",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I32 } },
    /* 0x5B */ WasmInstrDesc{ .name = "f32.eq",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x5C */ WasmInstrDesc{ .name = "f32.ne",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x5D */ WasmInstrDesc{ .name = "f32.lt",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x5E */ WasmInstrDesc{ .name = "f32.gt",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x5F */ WasmInstrDesc{ .name = "f32.le",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x60 */ WasmInstrDesc{ .name = "f32.ge",                     .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_I32 } },
    /* 0x61 */ WasmInstrDesc{ .name = "f64.eq",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x62 */ WasmInstrDesc{ .name = "f64.ne",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x63 */ WasmInstrDesc{ .name = "f64.lt",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x64 */ WasmInstrDesc{ .name = "f64.gt",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x65 */ WasmInstrDesc{ .name = "f64.le",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x66 */ WasmInstrDesc{ .name = "f64.ge",                     .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_I32 } },
    /* 0x67 */ WasmInstrDesc{ .name = "i32.clz",                    .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x68 */ WasmInstrDesc{ .name = "i32.ctz",                    .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x69 */ WasmInstrDesc{ .name = "i32.popcnt",                 .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0x6A */ WasmInstrDesc{ .name = "i32.add",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x6B */ WasmInstrDesc{ .name = "i32.sub",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x6C */ WasmInstrDesc{ .name = "i32.mul",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x6D */ WasmInstrDesc{ .name = "i32.div_s",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x6E */ WasmInstrDesc{ .name = "i32.div_u",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x6F */ WasmInstrDesc{ .name = "i32.rem_s",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x70 */ WasmInstrDesc{ .name = "i32.rem_u",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x71 */ WasmInstrDesc{ .name = "i32.and",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x72 */ WasmInstrDesc{ .name = "i32.or",                     .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x73 */ WasmInstrDesc{ .name = "i32.xor",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x74 */ WasmInstrDesc{ .name = "i32.shl",                    .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x75 */ WasmInstrDesc{ .name = "i32.shr_s",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x76 */ WasmInstrDesc{ .name = "i32.shr_u",                  .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x77 */ WasmInstrDesc{ .name = "i32.rotl",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x78 */ WasmInstrDesc{ .name = "i32.rotr",                   .param = { TYPE_I32, TYPE_I32 }, .result = { TYPE_I32 } },
    /* 0x79 */ WasmInstrDesc{ .name = "i64.clz",                    .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0x7A */ WasmInstrDesc{ .name = "i64.ctz",                    .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0x7B */ WasmInstrDesc{ .name = "i64.popcnt",                 .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0x7C */ WasmInstrDesc{ .name = "i64.add",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x7D */ WasmInstrDesc{ .name = "i64.sub",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x7E */ WasmInstrDesc{ .name = "i64.mul",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x7F */ WasmInstrDesc{ .name = "i64.div_s",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x80 */ WasmInstrDesc{ .name = "i64.div_u",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x81 */ WasmInstrDesc{ .name = "i64.rem_s",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x82 */ WasmInstrDesc{ .name = "i64.rem_u",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x83 */ WasmInstrDesc{ .name = "i64.and",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x84 */ WasmInstrDesc{ .name = "i64.or",                     .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x85 */ WasmInstrDesc{ .name = "i64.xor",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x86 */ WasmInstrDesc{ .name = "i64.shl",                    .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x87 */ WasmInstrDesc{ .name = "i64.shr_s",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x88 */ WasmInstrDesc{ .name = "i64.shr_u",                  .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x89 */ WasmInstrDesc{ .name = "i64.rotl",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x8A */ WasmInstrDesc{ .name = "i64.rotr",                   .param = { TYPE_I64, TYPE_I64 }, .result = { TYPE_I64 } },
    /* 0x8B */ WasmInstrDesc{ .name = "f32.abs",                    .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x8C */ WasmInstrDesc{ .name = "f32.neg",                    .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x8D */ WasmInstrDesc{ .name = "f32.ceil",                   .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x8E */ WasmInstrDesc{ .name = "f32.floor",                  .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x8F */ WasmInstrDesc{ .name = "f32.trunc",                  .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x90 */ WasmInstrDesc{ .name = "f32.nearest",                .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x91 */ WasmInstrDesc{ .name = "f32.sqrt",                   .param = { TYPE_F32 },           .result = { TYPE_F32 } },
    /* 0x92 */ WasmInstrDesc{ .name = "f32.add",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x93 */ WasmInstrDesc{ .name = "f32.sub",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x94 */ WasmInstrDesc{ .name = "f32.mul",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x95 */ WasmInstrDesc{ .name = "f32.div",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x96 */ WasmInstrDesc{ .name = "f32.min",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x97 */ WasmInstrDesc{ .name = "f32.max",                    .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x98 */ WasmInstrDesc{ .name = "f32.copysign",               .param = { TYPE_F32, TYPE_F32 }, .result = { TYPE_F32 } },
    /* 0x99 */ WasmInstrDesc{ .name = "f64.abs",                    .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9A */ WasmInstrDesc{ .name = "f64.neg",                    .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9B */ WasmInstrDesc{ .name = "f64.ceil",                   .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9C */ WasmInstrDesc{ .name = "f64.floor",                  .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9D */ WasmInstrDesc{ .name = "f64.trunc",                  .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9E */ WasmInstrDesc{ .name = "f64.nearest",                .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0x9F */ WasmInstrDesc{ .name = "f64.sqrt",                   .param = { TYPE_F64 },           .result = { TYPE_F64 } },
    /* 0xA0 */ WasmInstrDesc{ .name = "f64.add",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA1 */ WasmInstrDesc{ .name = "f64.sub",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA2 */ WasmInstrDesc{ .name = "f64.mul",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA3 */ WasmInstrDesc{ .name = "f64.div",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA4 */ WasmInstrDesc{ .name = "f64.min",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA5 */ WasmInstrDesc{ .name = "f64.max",                    .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA6 */ WasmInstrDesc{ .name = "f64.copysign",               .param = { TYPE_F64, TYPE_F64 }, .result = { TYPE_F64 } },
    /* 0xA7 */ WasmInstrDesc{ .name = "i32.wrap_i64",               .param = { TYPE_I64 },           .result = { TYPE_I32 } },
    /* 0xA8 */ WasmInstrDesc{ .name = "i32.trunc_f32_s",            .param = { TYPE_F32 },           .result = { TYPE_I32 } },
    /* 0xA9 */ WasmInstrDesc{ .name = "i32.trunc_f32_u",            .param = { TYPE_F32 },           .result = { TYPE_I32 } },
    /* 0xAA */ WasmInstrDesc{ .name = "i32.trunc_f64_s",            .param = { TYPE_F64 },           .result = { TYPE_I32 } },
    /* 0xAB */ WasmInstrDesc{ .name = "i32.trunc_f64_u",            .param = { TYPE_F64 },           .result = { TYPE_I32 } },
    /* 0xAC */ WasmInstrDesc{ .name = "i64.extend_i32_s",           .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0xAD */ WasmInstrDesc{ .name = "i64.extend_i32_u",           .param = { TYPE_I32 },           .result = { TYPE_I64 } },
    /* 0xAE */ WasmInstrDesc{ .name = "i64.trunc_f32_s",            .param = { TYPE_F32 },           .result = { TYPE_I64 } },
    /* 0xAF */ WasmInstrDesc{ .name = "i64.trunc_f32_u",            .param = { TYPE_F32 },           .result = { TYPE_I64 } },
    /* 0xB0 */ WasmInstrDesc{ .name = "i64.trunc_f64_s",            .param = { TYPE_F64 },           .result = { TYPE_I64 } },
    /* 0xB1 */ WasmInstrDesc{ .name = "i64.trunc_f64_u",            .param = { TYPE_F64 },           .result = { TYPE_I64 } },
    /* 0xB2 */ WasmInstrDesc{ .name = "f32.convert_i32_s",          .param = { TYPE_I32 },           .result = { TYPE_F32 } },
    /* 0xB3 */ WasmInstrDesc{ .name = "f32.convert_i32_u",          .param = { TYPE_I32 },           .result = { TYPE_F32 } },
    /* 0xB4 */ WasmInstrDesc{ .name = "f32.convert_i64_s",          .param = { TYPE_I64 },           .result = { TYPE_F32 } },
    /* 0xB5 */ WasmInstrDesc{ .name = "f32.convert_i64_u",          .param = { TYPE_I64 },           .result = { TYPE_F32 } },
    /* 0xB6 */ WasmInstrDesc{ .name = "f32.demote_f64",             .param = { TYPE_F64 },           .result = { TYPE_F32 } },
    /* 0xB7 */ WasmInstrDesc{ .name = "f64.convert_i32_s",          .param = { TYPE_I32 },           .result = { TYPE_F64 } },
    /* 0xB8 */ WasmInstrDesc{ .name = "f64.convert_i32_u",          .param = { TYPE_I32 },           .result = { TYPE_F64 } },
    /* 0xB9 */ WasmInstrDesc{ .name = "f64.convert_i64_s",          .param = { TYPE_I64 },           .result = { TYPE_F64 } },
    /* 0xBA */ WasmInstrDesc{ .name = "f64.convert_i64_u",          .param = { TYPE_I64 },           .result = { TYPE_F64 } },
    /* 0xBB */ WasmInstrDesc{ .name = "f64.promote_f32",            .param = { TYPE_F32 },           .result = { TYPE_F64 } },
    /* 0xBC */ WasmInstrDesc{ .name = "i32.reinterpret_f32",        .param = { TYPE_F32 },           .result = { TYPE_I32 } },
    /* 0xBD */ WasmInstrDesc{ .name = "i64.reinterpret_f64",        .param = { TYPE_F64 },           .result = { TYPE_I64 } },
    /* 0xBE */ WasmInstrDesc{ .name = "f32.reinterpret_i32",        .param = { TYPE_I32 },           .result = { TYPE_F32 } },
    /* 0xBF */ WasmInstrDesc{ .name = "f64.reinterpret_i64",        .param = { TYPE_I64 },           .result = { TYPE_F64 } },
    /* 0xC0 */ WasmInstrDesc{ .name = "i32.extend8_s",              .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0xC1 */ WasmInstrDesc{ .name = "i32.extend16_s",             .param = { TYPE_I32 },           .result = { TYPE_I32 } },
    /* 0xC2 */ WasmInstrDesc{ .name = "i64.extend8_s",              .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0xC3 */ WasmInstrDesc{ .name = "i64.extend16_s",             .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0xC4 */ WasmInstrDesc{ .name = "i64.extend32_s",             .param = { TYPE_I64 },           .result = { TYPE_I64 } },
    /* 0xC5 */ WasmInstrDesc{ },
    /* 0xC6 */ WasmInstrDesc{ },
    /* 0xC7 */ WasmInstrDesc{ },
    /* 0xC8 */ WasmInstrDesc{ },
    /* 0xC9 */ WasmInstrDesc{ },
    /* 0xCA */ WasmInstrDesc{ },
    /* 0xCB */ WasmInstrDesc{ },
    /* 0xCC */ WasmInstrDesc{ },
    /* 0xCD */ WasmInstrDesc{ },
    /* 0xCE */ WasmInstrDesc{ },
    /* 0xCF */ WasmInstrDesc{ },
    /* 0xD0 */ WasmInstrDesc{ .name = "ref.null",      .imm = "b" },
    /* 0xD1 */ WasmInstrDesc{ .name = "ref.is_null" },
    /* 0xD2 */ WasmInstrDesc{ .name = "ref.func",      .imm = "u" },
    /* 0xD3 */ WasmInstrDesc{ },
    /* 0xD4 */ WasmInstrDesc{ },
    /* 0xD5 */ WasmInstrDesc{ },
    /* 0xD6 */ WasmInstrDesc{ },
    /* 0xD7 */ WasmInstrDesc{ },
    /* 0xD8 */ WasmInstrDesc{ },
    /* 0xD9 */ WasmInstrDesc{ },
    /* 0xDA */ WasmInstrDesc{ },
    /* 0xDB */ WasmInstrDesc{ },
    /* 0xDC */ WasmInstrDesc{ },
    /* 0xDD */ WasmInstrDesc{ },
    /* 0xDE */ WasmInstrDesc{ },
    /* 0xDF */ WasmInstrDesc{ },
    /* 0xE0 */ WasmInstrDesc{ },
    /* 0xE1 */ WasmInstrDesc{ },
    /* 0xE2 */ WasmInstrDesc{ },
    /* 0xE3 */ WasmInstrDesc{ },
    /* 0xE4 */ WasmInstrDesc{ },
    /* 0xE5 */ WasmInstrDesc{ },
    /* 0xE6 */ WasmInstrDesc{ },
    /* 0xE7 */ WasmInstrDesc{ },
    /* 0xE8 */ WasmInstrDesc{ },
    /* 0xE9 */ WasmInstrDesc{ },
    /* 0xEA */ WasmInstrDesc{ },
    /* 0xEB */ WasmInstrDesc{ },
    /* 0xEC */ WasmInstrDesc{ },
    /* 0xED */ WasmInstrDesc{ },
    /* 0xEE */ WasmInstrDesc{ },
    /* 0xEF */ WasmInstrDesc{ },
    /* 0xF0 */ WasmInstrDesc{ },
    /* 0xF1 */ WasmInstrDesc{ },
    /* 0xF2 */ WasmInstrDesc{ },
    /* 0xF3 */ WasmInstrDesc{ },
    /* 0xF4 */ WasmInstrDesc{ },
    /* 0xF5 */ WasmInstrDesc{ },
    /* 0xF6 */ WasmInstrDesc{ },
    /* 0xF7 */ WasmInstrDesc{ },
    /* 0xF8 */ WasmInstrDesc{ },
    /* 0xF9 */ WasmInstrDesc{ },
    /* 0xFA */ WasmInstrDesc{ },
    /* 0xFB */ WasmInstrDesc{ },
    /* 0xFC */ WasmInstrDesc{ .name = "",              .imm = "*" }, // Extended instructions
    /* 0xFD */ WasmInstrDesc{ },
    /* 0xFE */ WasmInstrDesc{ },
    /* 0xFF */ WasmInstrDesc{ },
};

Array$<WasmInstrDesc$> extInstrDescTable = {
    /* 0xFC 0x00 */ WasmInstrDesc{ .name = "i32.trunc_sat_f32_s",             .param = { TYPE_F32 },                     .result = { TYPE_I32 } },
    /* 0xFC 0x01 */ WasmInstrDesc{ .name = "i32.trunc_sat_f32_u",             .param = { TYPE_F32 },                     .result = { TYPE_I32 } },
    /* 0xFC 0x02 */ WasmInstrDesc{ .name = "i32.trunc_sat_f64_s",             .param = { TYPE_F64 },                     .result = { TYPE_I32 } },
    /* 0xFC 0x03 */ WasmInstrDesc{ .name = "i32.trunc_sat_f64_u",             .param = { TYPE_F64 },                     .result = { TYPE_I32 } },
    /* 0xFC 0x04 */ WasmInstrDesc{ .name = "i64.trunc_sat_f32_s",             .param = { TYPE_F32 },                     .result = { TYPE_I64 } },
    /* 0xFC 0x05 */ WasmInstrDesc{ .name = "i64.trunc_sat_f32_u",             .param = { TYPE_F32 },                     .result = { TYPE_I64 } },
    /* 0xFC 0x06 */ WasmInstrDesc{ .name = "i64.trunc_sat_f64_s",             .param = { TYPE_F64 },                     .result = { TYPE_I64 } },
    /* 0xFC 0x07 */ WasmInstrDesc{ .name = "i64.trunc_sat_f64_u",             .param = { TYPE_F64 },                     .result = { TYPE_I64 } },
    /* 0xFC 0x08 */ WasmInstrDesc{ .name = "memory.init",        .imm = "u",  .param = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x09 */ WasmInstrDesc{ .name = "data.drop",          .imm = "u" },
    /* 0xFC 0x0A */ WasmInstrDesc{ .name = "memory.copy",        .imm = "bb", .param = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0B */ WasmInstrDesc{ .name = "memory.fill",        .imm = "b",  .param = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0C */ WasmInstrDesc{ .name = "table.init",         .imm = "uu", .param = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0D */ WasmInstrDesc{ .name = "elem.drop",          .imm = "u" },
    /* 0xFC 0x0E */ WasmInstrDesc{ .name = "table.copy",         .imm = "uu", .param = { TYPE_I32, TYPE_I32, TYPE_I32 } },
    /* 0xFC 0x0F */ WasmInstrDesc{ .name = "table.grow",         .imm = "u" },
    /* 0xFC 0x10 */ WasmInstrDesc{ .name = "table.size",         .imm = "u",                                             .result = { TYPE_I32 } },
    /* 0xFC 0x11 */ WasmInstrDesc{ .name = "table.fill",         .imm = "u" },
};
