name: Tests
on:
  workflow_dispatch:
jobs:
  triasm-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: npm update
        run: npm update
      - name: Run tests
        run: |
          cd test/triasm
          npx ts-node vectors.ts
  triasm-quickjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          path: quickjs
          repository: bellard/quickjs
          submodules: recursive
      - name: npm update
        run: npm update
      - name: Compile QuickJS
        run: |
          cd quickjs
          make -j`nproc` qjs
      - name: Run tests
        run: |
          npx tsc -p test/triasm/vectors.tsconfig.json
          cd test/triasm
          #time ../../quickjs/qjs --std vectors.js
          echo "import * as std from 'std';" > tmp.txt
          echo "import * as os from 'os';" > tmp.txt
          cat tmp.txt vectors.js > tmp.js
          ../../quickjs/qjsc \
            -flto -fbignum -fno-string-normalize -fno-module-loader -m \
            -o vectors tmp.js
          strip vectors
          time vectors
