name: Tests
on:
  workflow_dispatch:
jobs:
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build unit tests
        run: |
          cd test/unit
          make -j`nproc`
      - name: Run unit tests
        run: |
          cd test/unit
          make run
      - name: Check compilation errors
        run: |
          cd test/unit
          node test_build_errors.js
